// generated by `denext migrate` — safe to edit; re-running may overwrite
import type { DenextConfig } from "denext/server";
import pkg from "./package.json" with { type: "json" };

export default {
  mode: "spa",
  compatibilityMode: true,
  tailwind: { input: "./src/index.css", output: "./src/index.gen.css" },
  spa: {
    entry: "./src/bootstrap.ts",
    title: "T3 Code (Alpha)",
    env: {
      APP_VERSION: pkg.version,
      VITE_CLERK_CLI_OAUTH_CLIENT_ID: "",
      VITE_CLERK_JWT_TEMPLATE: "",
      VITE_CLERK_PUBLISHABLE_KEY: "",
      VITE_DEV_SERVER_URL: "",
      VITE_HOSTED_APP_CHANNEL: "",
      VITE_HOSTED_APP_URL: "",
      VITE_HTTP_URL: "",
      VITE_RELAY_OTLP_TRACES_DATASET: "",
      VITE_RELAY_OTLP_TRACES_TOKEN: "",
      VITE_RELAY_OTLP_TRACES_URL: "",
      VITE_T3CODE_RELAY_URL: "",
      VITE_WS_URL: "",
    },
    proxy: {
      prefixes: ["/api", "/oauth", "/.well-known", "/ws"],
      target: "http://127.0.0.1:3773",
    },
    // The designer's macOS master (dark appearance) instead of the auto-detected web touch icon.
    desktop: { icon: "../../assets/prod/black-macos-1024.png" },
  },
} satisfies DenextConfig;
