// generated by `denext migrate` — safe to edit; re-running may overwrite
// Entry for `deno desktop` — serves the static export in `out/` inside a native
// window (run `deno task export` first, or `deno task desktop`).
// Backend reverse proxy: set `spa.proxy` in denext.config.ts (e.g. to reach a
// local server same-origin so its session cookies persist).
import { runDesktop } from "denext/desktop";
import config from "./denext.config.ts";

await runDesktop({ importMetaUrl: import.meta.url, proxy: config.spa?.proxy });
