// denext-auth-session-template: 1 sha256=5e2ba11f63ea32dc60a4f426f1ecb437887b60e2719a4e3f8595b05447422093
// Generated by `denext mobile add auth-session` (denext auth sessions). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/desktop.

package dev.denext.authsession;

import android.app.Activity;
import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import androidx.annotation.Nullable;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * The native side of {@code openAuthSession()} from {@code denext/mobile}, reached from the web
 * app as {@code window.Capacitor.Plugins.DenextAuthSession}. {@code MainActivity} registers it
 * ({@code registerPlugin(DenextAuthSessionPlugin.class)} before {@code super.onCreate}).
 *
 * <ul>
 *   <li>{@code start({ url, callbackScheme }) → { url }}: opens {@code url} in a Custom Tab and
 *       resolves with the full callback URL when the app receives it: the provider redirects to
 *       {@code <callbackScheme>:…}, the app's VIEW intent filter for that scheme (written by
 *       {@code denext mobile add auth-session --scheme}) brings {@code MainActivity} back, and
 *       Capacitor hands the intent to {@link #handleOnNewIntent}. Rejects with code
 *       {@code cancelled} (the user came back without a callback, or {@code cancel} ran),
 *       {@code busy} (a session is already open), {@code invalid} (not an absolute https
 *       {@code url}, or not a custom scheme) or {@code unsupported} (no activity, or no browser).
 *   <li>{@code cancel()}: rejects the open {@code start} with {@code cancelled}. A Custom Tab
 *       cannot be closed from the app, so it stays open until the user leaves it.
 * </ul>
 *
 * <p>The Custom Tab is requested without the androidx.browser library: an ACTION_VIEW intent
 * carrying the Custom Tabs session extra, which a browser that supports Custom Tabs opens as
 * one and any other browser opens as a normal page. {@code preferEphemeral} has no effect here.
 *
 * <p>Cancel detection: returning to the app pauses and resumes {@code MainActivity}. A redirect
 * arrives as {@code onNewIntent}, which Android delivers before {@code onResume}; a resume with
 * no callback rejects {@code cancelled} after {@link #RESUME_CANCEL_DELAY_MS}, so a callback
 * that still races the resume wins.
 */
@CapacitorPlugin(name = "DenextAuthSession")
public class DenextAuthSessionPlugin extends Plugin {

    /** How long a resume without a callback waits before it rejects {@code cancelled}. */
    static final long RESUME_CANCEL_DELAY_MS = 800;
    /** The Custom Tabs protocol's session extra ({@code CustomTabsIntent.EXTRA_SESSION}). */
    private static final String EXTRA_CUSTOM_TABS_SESSION = "android.support.customtabs.extra.SESSION";
    private static final Pattern SCHEME = Pattern.compile("^[a-z][a-z0-9+.-]*$");
    /** Schemes that are not an app's own (the web, the OS, Capacitor's webview origin). */
    private static final Set<String> RESERVED_SCHEMES = new HashSet<>(Arrays.asList(
        "http", "https", "file", "content", "javascript", "data", "blob", "about", "mailto",
        "tel", "sms", "intent", "capacitor"
    ));

    private final Handler mainHandler = new Handler(Looper.getMainLooper());
    /** Main-thread only. The {@code start} call the open session answers. */
    @Nullable
    private PluginCall pending;
    /** Main-thread only. The callback scheme of the open session. */
    @Nullable
    private String pendingScheme;
    /** Main-thread only. Whether the activity paused since the session opened. */
    private boolean leftApp = false;
    private final Runnable resumeCancel = () -> rejectPending("the user closed the sign-in page", "cancelled");

    @PluginMethod
    public void start(PluginCall call) {
        Uri uri = httpsUri(call.getString("url"));
        if (uri == null) {
            call.reject("url must be an absolute https URL", "invalid");
            return;
        }
        String scheme = call.getString("callbackScheme");
        if (!isCustomScheme(scheme)) {
            call.reject("callbackScheme must be a custom URL scheme such as myapp", "invalid");
            return;
        }
        mainHandler.post(() -> begin(call, uri, scheme));
    }

    @PluginMethod
    public void cancel(PluginCall call) {
        mainHandler.post(() -> {
            rejectPending("the auth session was cancelled", "cancelled");
            call.resolve();
        });
    }

    /** Main thread. Opens the Custom Tab unless a session is already open. */
    private void begin(PluginCall call, Uri uri, String scheme) {
        if (pending != null) {
            call.reject("an auth session is already open", "busy");
            return;
        }
        Activity activity = getActivity();
        if (activity == null) {
            call.reject("no activity to open the sign-in page from", "unsupported");
            return;
        }
        pending = call;
        pendingScheme = scheme;
        leftApp = false;
        bridge.saveCall(call);
        try {
            activity.startActivity(customTabIntent(uri));
        } catch (ActivityNotFoundException e) {
            rejectPending("no browser can open the sign-in page", "unsupported");
        }
    }

    /** A VIEW intent for {@code uri} that a Custom Tabs browser opens as a Custom Tab. */
    static Intent customTabIntent(Uri uri) {
        Intent intent = new Intent(Intent.ACTION_VIEW, uri);
        Bundle extras = new Bundle();
        extras.putBinder(EXTRA_CUSTOM_TABS_SESSION, null);
        intent.putExtras(extras);
        intent.addCategory(Intent.CATEGORY_BROWSABLE);
        return intent;
    }

    @Override
    protected void handleOnNewIntent(Intent intent) {
        super.handleOnNewIntent(intent);
        if (pending == null || intent == null) return;
        Uri data = intent.getData();
        String scheme = data == null ? null : data.getScheme();
        if (scheme == null || !scheme.equalsIgnoreCase(pendingScheme)) return;
        PluginCall call = takePending();
        if (call == null) return;
        JSObject result = new JSObject();
        result.put("url", data.toString());
        call.resolve(result);
    }

    @Override
    protected void handleOnPause() {
        super.handleOnPause();
        if (pending == null) return;
        leftApp = true;
        mainHandler.removeCallbacks(resumeCancel);
    }

    @Override
    protected void handleOnResume() {
        super.handleOnResume();
        if (pending == null || !leftApp) return;
        mainHandler.removeCallbacks(resumeCancel);
        mainHandler.postDelayed(resumeCancel, RESUME_CANCEL_DELAY_MS);
    }

    @Override
    protected void handleOnDestroy() {
        rejectPending("the app closed during the auth session", "cancelled");
        super.handleOnDestroy();
    }

    /** Main thread. Clears the open session and returns its call (released from the bridge). */
    @Nullable
    private PluginCall takePending() {
        PluginCall call = pending;
        pending = null;
        pendingScheme = null;
        leftApp = false;
        mainHandler.removeCallbacks(resumeCancel);
        if (call != null) bridge.releaseCall(call);
        return call;
    }

    /** Main thread. Rejects the open session's call, if any, with {@code code}. */
    private void rejectPending(String message, String code) {
        PluginCall call = takePending();
        if (call != null) call.reject(message, code);
    }

    /** {@code raw} parsed when it is an absolute https URL with a host, else null. */
    @Nullable
    private static Uri httpsUri(@Nullable String raw) {
        if (raw == null) return null;
        Uri uri = Uri.parse(raw);
        String host = uri.getHost();
        return "https".equalsIgnoreCase(uri.getScheme()) && host != null && !host.isEmpty() ? uri : null;
    }

    /** A lower-case custom scheme: a letter, then letters, digits, {@code +}, {@code -} or {@code .}. */
    private static boolean isCustomScheme(@Nullable String scheme) {
        return scheme != null && SCHEME.matcher(scheme).matches() && !RESERVED_SCHEMES.contains(scheme);
    }
}
