// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota --force` to update it. See https://denext.dev/docs/desktop.

import Capacitor
import CryptoKit
import Foundation

/// The over-the-air UI's files and state. Versions live in `Application Support/denext-ota/<version>/`,
/// the state in UserDefaults:
///
/// - `current`: the confirmed downloaded version (nil: the bundled `public/` UI).
/// - `pending` / `previous`: a version on its trial launch, and what `current` was before it.
/// - `trialStarted`: the pending version has been loaded once. Finding it set at launch means
///   the app died before the UI confirmed its boot, so the version is rolled back unseen.
/// - `rejected`: the last version rolled back; `apply` refuses it (code `rejected`) until
///   `reset`, so a broken server UI cannot put the app in an apply → rollback loop.
/// - `staged`: a version `download` verified into its directory, waiting for `activate`. It is
///   never started on its own: launch only ever serves `pending` or `current`.
/// - `binaryVersion`: the app binary the downloads belong to. A new binary brings its own
///   bundled UI (and maybe new native code), so every download is dropped.
///
/// Main-thread only, apart from `download` and the read-only helpers it uses.
final class DenextOtaStore {
    static let shared = DenextOtaStore()
    static let watchdogSeconds: TimeInterval = 15
    /// The UI bundled with the app (`cap sync` copies the web export here).
    static let bundledDirectory = Bundle.main.url(forResource: "public", withExtension: nil)
    /// The manifest inside a UI directory, as `denext export` (`spa.ota`) and
    /// `denext ota manifest` write it.
    static let manifestPath = "_denext/ota.json"

    private static let maxConcurrentDownloads = 6
    private static let perFileTimeout: TimeInterval = 30

    private enum Key {
        static let current = "denext.ota.current"
        static let pending = "denext.ota.pending"
        static let previous = "denext.ota.previous"
        static let trialStarted = "denext.ota.trialStarted"
        static let rejected = "denext.ota.rejected"
        static let staged = "denext.ota.staged"
        static let binaryVersion = "denext.ota.binaryVersion"
    }

    struct OtaError: LocalizedError {
        let code: String
        let message: String
        var errorDescription: String? { message }
    }

    struct ManifestFile {
        let path: String
        let sha256: String
        let size: Int
    }

    struct ApplyRequest {
        let baseUrl: URL
        let headers: [String: String]
        let version: String
        let files: [ManifestFile]

        init(baseUrl: String?, headers: JSObject?, manifest: JSObject?) throws {
            guard let baseUrl = baseUrl.flatMap(URL.init(string:)),
                  let scheme = baseUrl.scheme?.lowercased(), scheme == "http" || scheme == "https",
                  baseUrl.host != nil else {
                throw OtaError(code: "invalid", message: "baseUrl must be an http(s) URL.")
            }
            var headerFields: [String: String] = [:]
            for (name, value) in headers ?? [:] {
                if let value = value as? String { headerFields[name] = value }
            }
            guard let manifest = manifest,
                  let version = manifest["version"] as? String, DenextOtaStore.isSha256(version),
                  let rawFiles = manifest["files"] as? JSArray, !rawFiles.isEmpty else {
                throw OtaError(code: "invalid", message: "The manifest is malformed.")
            }
            var files: [ManifestFile] = []
            var seen = Set<String>()
            for rawFile in rawFiles {
                guard let file = rawFile as? JSObject,
                      let path = file["path"] as? String, DenextOtaStore.isSafeRelativePath(path),
                      path != DenextOtaStore.manifestPath, !seen.contains(path),
                      let sha256 = file["sha256"] as? String, DenextOtaStore.isSha256(sha256),
                      let size = (file["size"] as? NSNumber)?.intValue, size >= 0 else {
                    throw OtaError(code: "invalid", message: "The manifest lists a malformed file.")
                }
                seen.insert(path)
                files.append(ManifestFile(path: path, sha256: sha256, size: size))
            }
            guard seen.contains("index.html") else {
                throw OtaError(code: "invalid", message: "The manifest has no index.html.")
            }
            self.baseUrl = baseUrl
            self.headers = headerFields
            self.version = version
            self.files = files
        }
    }

    /// What `download` did: files fetched over the network, and files copied from a UI
    /// already on the device (the running download or the bundled `public/`).
    struct DownloadStats {
        var downloaded = 0
        var copied = 0
    }

    private let defaults = UserDefaults.standard
    private let fileManager = FileManager.default
    private var launchPrepared = false

    let root: URL = {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return support.appendingPathComponent("denext-ota", isDirectory: true)
    }()

    private(set) var current: String? {
        get { defaults.string(forKey: Key.current) }
        set { defaults.set(newValue, forKey: Key.current) }
    }
    private(set) var pending: String? {
        get { defaults.string(forKey: Key.pending) }
        set { defaults.set(newValue, forKey: Key.pending) }
    }
    private var previous: String? {
        get { defaults.string(forKey: Key.previous) }
        set { defaults.set(newValue, forKey: Key.previous) }
    }
    private var trialStarted: Bool {
        get { defaults.bool(forKey: Key.trialStarted) }
        set { defaults.set(newValue, forKey: Key.trialStarted) }
    }
    private(set) var rejected: String? {
        get { defaults.string(forKey: Key.rejected) }
        set { defaults.set(newValue, forKey: Key.rejected) }
    }
    private var stagedVersion: String? {
        get { defaults.string(forKey: Key.staged) }
        set { defaults.set(newValue, forKey: Key.staged) }
    }
    /// The staged version, while its verified directory is still there.
    var staged: String? {
        return stagedVersion.flatMap { hasVersion($0) ? $0 : nil }
    }

    /// The version stamped into the bundled UI (`public/_denext/ota.json`), if any.
    lazy var bundledVersion: String? = {
        guard let directory = DenextOtaStore.bundledDirectory,
              let object = DenextOtaStore.readManifest(in: directory),
              let version = object["version"] as? String, DenextOtaStore.isSha256(version) else {
            return nil
        }
        return version
    }()

    static func isSha256(_ value: String) -> Bool {
        return value.count == 64 && value.allSatisfy { $0.isHexDigit && !$0.isUppercase }
    }

    /// A forward-slash path that stays inside its directory: no empty, `.` or `..` segments,
    /// no leading slash, no backslashes or NULs.
    static func isSafeRelativePath(_ path: String) -> Bool {
        guard !path.isEmpty, !path.contains("\\"), !path.contains("\0") else { return false }
        return path.split(separator: "/", omittingEmptySubsequences: false).allSatisfy { segment in
            !segment.isEmpty && segment != "." && segment != ".."
        }
    }

    static func sha256Hex(_ data: Data) -> String {
        return SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// `<directory>/_denext/ota.json` as a JSON object, if present and readable.
    static func readManifest(in directory: URL) -> [String: Any]? {
        let url = directory.appendingPathComponent(manifestPath, isDirectory: false)
        guard let data = try? Data(contentsOf: url) else { return nil }
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    /// `path` inside `directory`, or nil when it would resolve outside it.
    static func file(_ path: String, in directory: URL) -> URL? {
        guard isSafeRelativePath(path) else { return nil }
        let target = directory.appendingPathComponent(path, isDirectory: false)
        let base = directory.standardizedFileURL.path
        return target.standardizedFileURL.path.hasPrefix(base.hasSuffix("/") ? base : base + "/") ? target : nil
    }

    func versionDirectory(_ version: String) -> URL {
        return root.appendingPathComponent(version, isDirectory: true)
    }

    private func hasVersion(_ version: String) -> Bool {
        return fileManager.fileExists(atPath: versionDirectory(version).appendingPathComponent("index.html").path)
    }

    // MARK: Launch

    /// Called before the bridge loads the first page. Returns the directory to serve (nil:
    /// the bundled UI) and whether this launch is a pending version's trial, which the caller
    /// guards with the watchdog. The first call in a process is the launch; a later one (a
    /// second bridge view controller) keeps serving the active UI instead of counting again.
    func prepareLaunch() -> (directory: URL?, trial: Bool) {
        if launchPrepared {
            if let pending = pending, hasVersion(pending) { return (versionDirectory(pending), true) }
            if let current = current, hasVersion(current) { return (versionDirectory(current), false) }
            return (nil, false)
        }
        launchPrepared = true
        // A new app binary brings its own bundled UI (and maybe new native code), so a UI
        // downloaded for the old binary is dropped, as Capacitor drops its own deploy path. The
        // bundled UI's version is part of the key, so a rebuild that ships a different UI
        // counts as a new binary even when its version and build numbers were not bumped.
        let binaryVersion = [
            Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "",
            Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "",
            bundledVersion ?? ""
        ].joined(separator: "+")
        if defaults.string(forKey: Key.binaryVersion) != binaryVersion {
            reset()
            defaults.set(binaryVersion, forKey: Key.binaryVersion)
            return (nil, false)
        }
        if let pending = pending {
            if !trialStarted && hasVersion(pending) {
                trialStarted = true
                return (versionDirectory(pending), true)
            }
            // The app died during the trial (or the files are gone): roll back before loading.
            CAPLog.print("denext OTA: UI \(pending) never confirmed its boot; rolling back.")
            return (rollBackPending(), false)
        }
        if let current = current {
            if hasVersion(current) {
                return (versionDirectory(current), false)
            }
            self.current = nil
        }
        return (nil, false)
    }

    // MARK: Transitions

    /// Records a verified `version` as staged, deleting the directory of the version it
    /// replaces unless that one is current, pending or bundled.
    func stage(_ version: String) {
        if let old = stagedVersion, old != version, old != current, old != pending, old != bundledVersion {
            try? fileManager.removeItem(at: versionDirectory(old))
        }
        stagedVersion = version
    }

    /// `activate` / `apply`: `version` (the staged one) starts its trial; nothing stays staged.
    func beginTrial(_ version: String) {
        previous = current
        pending = version
        trialStarted = true
        stagedVersion = nil
    }

    /// `booted`: the pending version becomes current, and every other version is deleted
    /// (bar a staged one).
    func confirmPending() {
        guard let pending = pending else { return }
        current = pending
        self.pending = nil
        previous = nil
        trialStarted = false
        prune(keeping: [pending, stagedVersion].compactMap { $0 })
    }

    /// Drops the pending version (remembered as rejected) and returns the directory to serve:
    /// the previous version if it is still there, otherwise nil for the bundled UI.
    func rollBackPending() -> URL? {
        let target = previous.flatMap { hasVersion($0) ? $0 : nil }
        if let failed = pending {
            rejected = failed
            try? fileManager.removeItem(at: versionDirectory(failed))
        }
        pending = nil
        previous = nil
        trialStarted = false
        current = target
        return target.map(versionDirectory)
    }

    /// Back to the bundled UI with no downloaded or staged versions and nothing rejected.
    func reset() {
        for key in [Key.current, Key.pending, Key.previous, Key.trialStarted, Key.rejected, Key.staged] {
            defaults.removeObject(forKey: key)
        }
        try? fileManager.removeItem(at: root)
    }

    private func prune(keeping versions: [String]) {
        guard let entries = try? fileManager.contentsOfDirectory(at: root, includingPropertiesForKeys: nil) else {
            return
        }
        for entry in entries where !versions.contains(entry.lastPathComponent) {
            try? fileManager.removeItem(at: entry)
        }
    }

    // MARK: Download

    /// A UI already on the device that files can be copied from, with its manifest's
    /// SHA-256 → path index.
    private struct LocalSource {
        let directory: URL
        let pathsBySha: [String: String]
    }

    /// The running download (if any), then the bundled UI.
    private func localSources() -> [LocalSource] {
        var directories: [URL] = []
        if let current = current, hasVersion(current) { directories.append(versionDirectory(current)) }
        if let bundled = DenextOtaStore.bundledDirectory { directories.append(bundled) }
        return directories.map { directory in
            var index: [String: String] = [:]
            for case let file as [String: Any] in (DenextOtaStore.readManifest(in: directory)?["files"] as? [Any]) ?? [] {
                if let sha = file["sha256"] as? String, let path = file["path"] as? String, index[sha] == nil {
                    index[sha] = path
                }
            }
            return LocalSource(directory: directory, pathsBySha: index)
        }
    }

    /// The bytes of `file` from a UI already on the device, when one has a file with the
    /// same SHA-256 (by its manifest, or at the same path) that still verifies.
    private func localCopy(of file: ManifestFile, from sources: [LocalSource]) -> Data? {
        for source in sources {
            var candidates: [String] = []
            if let path = source.pathsBySha[file.sha256] { candidates.append(path) }
            if !candidates.contains(file.path) { candidates.append(file.path) }
            for candidate in candidates {
                guard let url = DenextOtaStore.file(candidate, in: source.directory),
                      let data = try? Data(contentsOf: url),
                      data.count == file.size, DenextOtaStore.sha256Hex(data) == file.sha256 else {
                    continue
                }
                return data
            }
        }
        return nil
    }

    /// Off the main thread. Fetches and verifies every file into `<version>.partial/` (copying
    /// the ones a UI on the device already has), writes the manifest next to them, then
    /// renames the directory to `<version>/`. Any failure deletes the partial directory.
    func download(_ request: ApplyRequest) async throws -> DownloadStats {
        let partial = root.appendingPathComponent("\(request.version).partial", isDirectory: true)
        let destination = versionDirectory(request.version)
        try? fileManager.removeItem(at: partial)
        do {
            try fileManager.createDirectory(at: partial, withIntermediateDirectories: true)
            let sources = localSources()
            let configuration = URLSessionConfiguration.ephemeral
            configuration.timeoutIntervalForRequest = DenextOtaStore.perFileTimeout
            configuration.timeoutIntervalForResource = DenextOtaStore.perFileTimeout * 2
            configuration.requestCachePolicy = .reloadIgnoringLocalCacheData
            let session = URLSession(configuration: configuration)
            defer { session.finishTasksAndInvalidate() }

            let stats = try await withThrowingTaskGroup(of: Bool.self, returning: DownloadStats.self) { group in
                var stats = DownloadStats()
                var remaining = request.files.makeIterator()
                for _ in 0..<DenextOtaStore.maxConcurrentDownloads {
                    guard let file = remaining.next() else { break }
                    group.addTask {
                        try await self.fetchFile(file, request: request, session: session, sources: sources, into: partial)
                    }
                }
                while let copied = try await group.next() {
                    if copied { stats.copied += 1 } else { stats.downloaded += 1 }
                    if let file = remaining.next() {
                        group.addTask {
                            try await self.fetchFile(file, request: request, session: session, sources: sources, into: partial)
                        }
                    }
                }
                return stats
            }
            try writeManifest(request, into: partial)
            try? fileManager.removeItem(at: destination)
            try fileManager.moveItem(at: partial, to: destination)
            return stats
        } catch {
            try? fileManager.removeItem(at: partial)
            throw error
        }
    }

    /// The version's own `_denext/ota.json`, so a later update can copy files from it.
    private func writeManifest(_ request: ApplyRequest, into directory: URL) throws {
        let files = request.files.map { ["path": $0.path, "sha256": $0.sha256, "size": $0.size] as [String: Any] }
        let data = try JSONSerialization.data(withJSONObject: ["version": request.version, "files": files])
        let target = directory.appendingPathComponent(DenextOtaStore.manifestPath, isDirectory: false)
        try fileManager.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: target, options: .atomic)
    }

    /// Writes one verified file into `directory`; returns true when it was copied from the
    /// device rather than downloaded.
    private func fetchFile(
        _ file: ManifestFile,
        request: ApplyRequest,
        session: URLSession,
        sources: [LocalSource],
        into directory: URL
    ) async throws -> Bool {
        guard let target = DenextOtaStore.file(file.path, in: directory) else {
            throw OtaError(code: "invalid", message: "\(file.path) leaves the UI directory.")
        }
        let copied: Bool
        let data: Data
        if let local = localCopy(of: file, from: sources) {
            data = local
            copied = true
        } else {
            data = try await downloadFile(file, request: request, session: session)
            copied = false
        }
        try fileManager.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: target, options: .atomic)
        return copied
    }

    private func downloadFile(_ file: ManifestFile, request: ApplyRequest, session: URLSession) async throws -> Data {
        var url = request.baseUrl
        for segment in file.path.split(separator: "/") {
            url.appendPathComponent(String(segment))
        }
        var urlRequest = URLRequest(url: url, timeoutInterval: DenextOtaStore.perFileTimeout)
        for (name, value) in request.headers {
            urlRequest.setValue(value, forHTTPHeaderField: name)
        }
        let (data, response) = try await session.data(for: urlRequest)
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard status == 200 else {
            throw OtaError(code: "download", message: "Downloading \(file.path) failed with HTTP \(status).")
        }
        guard data.count == file.size, DenextOtaStore.sha256Hex(data) == file.sha256 else {
            throw OtaError(code: "integrity", message: "\(file.path) does not match the manifest.")
        }
        return data
    }
}
