// denext-ota-template: 3 sha256=0bda4f8181120889d4761bd72eb0fd86747c746d57d375e79cdbc6eef4567e79
// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota` after upgrading denext (then ship a new binary). See
// https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import CryptoKit
import Foundation

/// The over-the-air UI's files and state. Versions live in `Application Support/denext-ota/<version>/`
/// (excluded from iCloud/iTunes backup), the state in UserDefaults:
///
/// - `current`: the confirmed downloaded version (nil: the bundled `public/` UI).
/// - `pending` / `previous`: a version on its trial launch, and what `current` was before it.
/// - `trialAttempts`: how many launches the pending version has had without confirming its boot.
///   A launch that finds `maxTrialAttempts` already used rolls the version back unseen, so one
///   process death (the OS killing a backgrounded app, say) does not reject a good UI, but a UI
///   that kills the app every time is rolled back on the launch after its second try.
/// - `rejected`: the last version rolled back; `apply` refuses it (code `rejected`) until
///   `reset`, so a broken server UI cannot put the app in an apply → rollback loop.
/// - `staged`: a version `download` verified into its directory, waiting for `activate`. It is
///   never started on its own: launch only ever serves `pending` or `current`.
/// - `sequence`: the highest manifest `sequence` accepted on this device. A manifest with a lower
///   one, or without one once any was accepted, is refused (code `downgrade`). It survives
///   `reset` and new binaries: only a reinstall clears it.
/// - `binaryVersion`: the app binary the downloads belong to. A new binary brings its own
///   bundled UI (and maybe new native code), so every download is dropped.
///
/// Main-thread only, apart from `download`, the request parse and the read-only helpers they use.
final class DenextOtaStore: @unchecked Sendable {
    static let shared = DenextOtaStore()
    /// The UI bundled with the app (`cap sync` copies the web export here).
    static let bundledDirectory = Bundle.main.url(forResource: "public", withExtension: nil)
    /// The manifest inside a UI directory, as `denext export` (`spa.ota`) and
    /// `denext ota manifest` write it.
    static let manifestPath = "_denext/ota.json"

    /// The Info.plist number key holding the boot timeout in seconds (default 15).
    static let bootTimeoutInfoKey = "DenextOtaBootTimeout"
    /// Seconds of foreground time a UI on its trial launch has to call `booted` (1 … 600).
    static let bootTimeout: TimeInterval = {
        let value = Bundle.main.object(forInfoDictionaryKey: DenextOtaStore.bootTimeoutInfoKey)
        let seconds = (value as? NSNumber)?.doubleValue ?? (value as? String).flatMap { Double($0) } ?? 15
        return min(max(seconds, 1), 600)
    }()
    /// Launches a pending version gets before it is rolled back unseen.
    static let maxTrialAttempts = 2
    /// The most files a manifest may list.
    static let maxFiles = 20_000
    /// The most bytes a manifest's files may add up to (512 MiB).
    static let maxTotalBytes: Int64 = 512 * 1024 * 1024
    /// The longest a whole `download` / `apply` may take before it is cancelled.
    static let applyDeadline: TimeInterval = 30 * 60
    static let maxConcurrentDownloads = 6
    /// The longest a download may go without receiving a byte.
    static let idleTimeout: TimeInterval = 30
    /// The longest one file may take: 30 s, plus what a 32 KiB/s link needs for its size.
    static func fileDeadline(size: Int64) -> TimeInterval {
        return 30 + Double(size) / 32_768
    }

    private enum Key {
        static let current = "denext.ota.current"
        static let pending = "denext.ota.pending"
        static let previous = "denext.ota.previous"
        /// Written by earlier templates; cleared wherever the trial state is.
        static let legacyTrialStarted = "denext.ota.trialStarted"
        static let trialAttempts = "denext.ota.trialAttempts"
        static let rejected = "denext.ota.rejected"
        static let staged = "denext.ota.staged"
        static let sequence = "denext.ota.sequence"
        static let binaryVersion = "denext.ota.binaryVersion"
    }

    struct OtaError: LocalizedError {
        let code: String
        let message: String
        var errorDescription: String? { message }
    }

    struct ManifestFile: Sendable {
        let path: String
        let sha256: String
        let size: Int64
    }

    /// The request `download` and `apply` take. Building one is the whole trust check, done
    /// before anything is downloaded or any state changes: the manifest must be well formed and
    /// within the caps (code `invalid`), the file list must hash to its `version` (code
    /// `integrity`), `checkTrust` must accept the signature or the transport (codes `signature` /
    /// `insecure`), and `checkRelease` its `sequence` and `minNative` (codes `downgrade` /
    /// `native_too_old`).
    struct ApplyRequest: Sendable {
        let baseUrl: URL
        let headers: [String: String]
        let version: String
        let files: [ManifestFile]
        let sequence: Int64?

        init(baseUrl: String?, headers: JSObject?, manifest: JSObject?) throws {
            guard let baseUrl = baseUrl.flatMap(URL.init(string:)),
                  let scheme = baseUrl.scheme?.lowercased(), scheme == "http" || scheme == "https",
                  baseUrl.host != nil else {
                throw OtaError(code: "invalid", message: "baseUrl must be an http(s) URL.")
            }
            var headerFields: [String: String] = [:]
            for (name, value) in headers ?? [:] {
                if let value = value as? String { headerFields[name] = value }
            }
            guard let manifest = manifest,
                  let version = manifest["version"] as? String, DenextOtaStore.isSha256(version),
                  let rawFiles = manifest["files"] as? JSArray, !rawFiles.isEmpty else {
                throw OtaError(code: "invalid", message: "The manifest is malformed.")
            }
            let files = try DenextOtaStore.parseFiles(rawFiles)
            let sequence = try DenextOtaStore.releaseInteger(manifest["sequence"], name: "sequence")
            let minNative = try DenextOtaStore.releaseInteger(manifest["minNative"], name: "minNative")
            // The version is recomputed from the files, never trusted: files → version → signature.
            guard DenextOtaStore.manifestVersion(files) == version else {
                throw OtaError(code: "integrity", message: "The manifest version does not match its files.")
            }
            try DenextOtaStore.checkTrust(
                baseUrl: baseUrl,
                payload: DenextOtaStore.signaturePayload(
                    version: version,
                    required: (manifest["required"] as? Bool) ?? false,
                    notes: (manifest["notes"] as? String) ?? "",
                    sequence: sequence,
                    minNative: minNative
                ),
                signature: manifest["signature"] as? String
            )
            try DenextOtaStore.checkRelease(sequence: sequence, minNative: minNative)
            self.baseUrl = baseUrl
            self.headers = headerFields
            self.version = version
            self.files = files
            self.sequence = sequence
        }
    }

    /// What `download` did: files fetched over the network, and files copied from a UI
    /// already on the device (the running download, the bundled `public/`, or an earlier,
    /// interrupted attempt at the same version).
    struct DownloadStats: Sendable {
        var downloaded = 0
        var copied = 0
    }

    private let defaults = UserDefaults.standard
    private let fileManager = FileManager.default
    private var launchPrepared = false

    let root: URL = {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return support.appendingPathComponent("denext-ota", isDirectory: true)
    }()

    private(set) var current: String? {
        get { defaults.string(forKey: Key.current) }
        set { defaults.set(newValue, forKey: Key.current) }
    }
    private(set) var pending: String? {
        get { defaults.string(forKey: Key.pending) }
        set { defaults.set(newValue, forKey: Key.pending) }
    }
    private var previous: String? {
        get { defaults.string(forKey: Key.previous) }
        set { defaults.set(newValue, forKey: Key.previous) }
    }
    private var trialAttempts: Int {
        get { defaults.integer(forKey: Key.trialAttempts) }
        set { defaults.set(newValue, forKey: Key.trialAttempts) }
    }
    private(set) var rejected: String? {
        get { defaults.string(forKey: Key.rejected) }
        set { defaults.set(newValue, forKey: Key.rejected) }
    }
    private var stagedVersion: String? {
        get { defaults.string(forKey: Key.staged) }
        set { defaults.set(newValue, forKey: Key.staged) }
    }
    /// The staged version, while its verified directory is still there.
    var staged: String? {
        return stagedVersion.flatMap { hasVersion($0) ? $0 : nil }
    }
    /// The highest manifest `sequence` accepted on this device, if any.
    var highestSequence: Int64? {
        return (defaults.object(forKey: Key.sequence) as? NSNumber)?.int64Value
    }

    /// The version stamped into the bundled UI (`public/_denext/ota.json`), if any.
    lazy var bundledVersion: String? = {
        guard let directory = DenextOtaStore.bundledDirectory,
              let object = DenextOtaStore.readManifest(in: directory),
              let version = object["version"] as? String, DenextOtaStore.isSha256(version) else {
            return nil
        }
        return version
    }()

    /// Whether `value` is 64 lowercase ASCII hex digits.
    static func isSha256(_ value: String) -> Bool {
        let utf8 = value.utf8
        return utf8.count == 64 && utf8.allSatisfy { (48...57).contains($0) || (97...102).contains($0) }
    }

    /// The `/`-separated segments of `path`, split on its UTF-8 bytes (never on grapheme clusters,
    /// which could glue a `/` to a following combining mark).
    static func segments(_ path: String) -> [String] {
        return path.utf8.split(separator: UInt8(ascii: "/"), omittingEmptySubsequences: false)
            .map { String(decoding: $0, as: UTF8.self) }
    }

    /// A forward-slash path that stays inside its directory: no empty, `.` or `..` segments,
    /// no leading slash, no backslashes, and no control characters (U+0000–U+001F, U+007F, which
    /// could forge the lines the version hashes). Checked on Unicode scalars, not characters.
    static func isSafeRelativePath(_ path: String) -> Bool {
        guard !path.isEmpty,
              !path.unicodeScalars.contains(where: { $0.value < 0x20 || $0.value == 0x7F || $0 == "\\" }) else {
            return false
        }
        return path.utf8.split(separator: UInt8(ascii: "/"), omittingEmptySubsequences: false).allSatisfy { segment in
            !segment.isEmpty && !segment.elementsEqual(".".utf8) && !segment.elementsEqual("..".utf8)
        }
    }

    /// The manifest's `files`, checked one by one and against the caps.
    static func parseFiles(_ rawFiles: JSArray) throws -> [ManifestFile] {
        guard rawFiles.count <= maxFiles else {
            throw OtaError(code: "invalid", message: "The manifest lists more than \(maxFiles) files.")
        }
        var files: [ManifestFile] = []
        var seen = Set<String>()
        var total: Int64 = 0
        for rawFile in rawFiles {
            guard let file = rawFile as? JSObject,
                  let path = file["path"] as? String, isSafeRelativePath(path),
                  path != manifestPath, !seen.contains(path),
                  let sha256 = file["sha256"] as? String, isSha256(sha256),
                  let size = try? releaseInteger(file["size"], name: "size") else {
                throw OtaError(code: "invalid", message: "The manifest lists a malformed file.")
            }
            total += size
            guard total <= maxTotalBytes else {
                throw OtaError(code: "invalid", message: "The manifest's files add up to more than \(maxTotalBytes) bytes.")
            }
            seen.insert(path)
            files.append(ManifestFile(path: path, sha256: sha256, size: size))
        }
        guard seen.contains("index.html") else {
            throw OtaError(code: "invalid", message: "The manifest has no index.html.")
        }
        return files
    }

    /// A JSON integer in 0 … 2^53 − 1 (nil when absent); anything else is `invalid`.
    static func releaseInteger(_ value: Any?, name: String) throws -> Int64? {
        guard let value = value, !(value is NSNull) else { return nil }
        guard let number = value as? NSNumber, CFGetTypeID(number) != CFBooleanGetTypeID(),
              number.doubleValue >= 0, number.doubleValue <= 9_007_199_254_740_991,
              number.doubleValue.rounded(.towardZero) == number.doubleValue else {
            throw OtaError(code: "invalid", message: "The manifest's \(name) is not a non-negative integer.")
        }
        return number.int64Value
    }

    static func hex<D: Sequence>(_ digest: D) -> String where D.Element == UInt8 {
        return digest.map { String(format: "%02x", $0) }.joined()
    }

    static func sha256Hex(_ data: Data) -> String {
        return hex(SHA256.hash(data: data))
    }

    // MARK: Trust

    /// The Info.plist string key holding the OTA public key: base64 of the DER SubjectPublicKeyInfo
    /// of an ECDSA P-256 key (`denext mobile add-ota --public-key`). Read from the app binary only.
    static let publicKeyInfoKey = "DenextOtaPublicKey"
    /// The hosts an unsigned UI may come from over plain http when no public key is embedded.
    static let loopbackHosts: Set<String> = ["localhost", "127.0.0.1", "::1", "[::1]"]

    enum PublicKeyConfig {
        case unset
        case invalid
        case key(P256.Signing.PublicKey)
    }

    /// The embedded public key. A value that is present but does not parse is `invalid`, which
    /// refuses every manifest (fail closed) rather than falling back to unsigned updates.
    static let publicKey: PublicKeyConfig = {
        guard let text = (Bundle.main.object(forInfoDictionaryKey: DenextOtaStore.publicKeyInfoKey) as? String)?
            .trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty else {
            return .unset
        }
        guard let der = Data(base64Encoded: text),
              let key = try? P256.Signing.PublicKey(derRepresentation: der) else {
            return .invalid
        }
        return .key(key)
    }()

    /// The app binary's build number (`CFBundleVersion`) as an integer, which a manifest's
    /// `minNative` is compared with: the whole value when it is an integer, else its first
    /// dot-separated component, else 0.
    static let nativeBuild: Int64 = {
        let text = (Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "")
            .trimmingCharacters(in: .whitespaces)
        return Int64(text) ?? text.split(separator: ".").first.flatMap { Int64($0) } ?? 0
    }()

    /// The manifest version of `files`: SHA-256 over the `"<path>\t<sha256>\n"` lines sorted by
    /// path in UTF-16 code-unit order, exactly as `otaManifestVersion` in denext computes it.
    static func manifestVersion(_ files: [ManifestFile]) -> String {
        let lines = files
            .sorted { $0.path.utf16.lexicographicallyPrecedes($1.path.utf16) }
            .map { "\($0.path)\t\($0.sha256)\n" }
            .joined()
        return sha256Hex(Data(lines.utf8))
    }

    /// The bytes a manifest signature covers (denext's `otaSignaturePayload`), UTF-8 with `\n`
    /// separators and no trailing newline. With a `sequence` (v2):
    /// `"denext-ota-v2\n" + version + "\n" + ("1" | "0") + "\n" + sha256hex(notes) + "\n" +
    /// sequence + "\n" + (minNative or "")`; without one (v1):
    /// `"denext-ota-v1\n" + version + "\n" + ("1" | "0") + "\n" + sha256hex(notes)`.
    static func signaturePayload(version: String, required: Bool, notes: String, sequence: Int64?, minNative: Int64?) -> Data {
        let head = "\(version)\n\(required ? "1" : "0")\n\(sha256Hex(Data(notes.utf8)))"
        guard let sequence = sequence else {
            return Data("denext-ota-v1\n\(head)".utf8)
        }
        return Data("denext-ota-v2\n\(head)\n\(sequence)\n\(minNative.map { String($0) } ?? "")".utf8)
    }

    /// The download policy, checked before any file is fetched. With a public key embedded, the
    /// manifest must carry a valid signature over `payload` (code `signature`), whatever the
    /// transport. Without one, only https, or plain http to a loopback host, is allowed (code
    /// `insecure`). A signature protects integrity only: over plain http the request headers
    /// (bearer tokens) still cross the network in the clear.
    static func checkTrust(baseUrl: URL, payload: Data, signature: String?) throws {
        switch publicKey {
        case .key(let key):
            guard let signature = signature,
                  let raw = Data(base64Encoded: signature),
                  let ecdsa = try? P256.Signing.ECDSASignature(rawRepresentation: raw),
                  key.isValidSignature(ecdsa, for: payload) else {
                throw OtaError(code: "signature", message: "The manifest signature is missing or does not verify.")
            }
        case .invalid:
            throw OtaError(code: "signature", message: "Info.plist \(publicKeyInfoKey) is not a base64 P-256 public key.")
        case .unset:
            let host = (baseUrl.host ?? "").lowercased()
            guard baseUrl.scheme?.lowercased() == "https" || loopbackHosts.contains(host) else {
                throw OtaError(
                    code: "insecure",
                    message: "Refusing an unsigned UI over plain http from \(host); use https or embed a public key."
                )
            }
        }
    }

    /// The release policy, checked after `checkTrust` (so a signed manifest's values are
    /// authentic) and before any file is fetched: no `sequence` below the highest this device
    /// accepted, and none missing once one was (code `downgrade`); no `minNative` above this
    /// binary's build number (code `native_too_old`).
    static func checkRelease(sequence: Int64?, minNative: Int64?) throws {
        if let highest = shared.highestSequence {
            guard let sequence = sequence else {
                throw OtaError(code: "downgrade", message: "The manifest has no sequence, but this device accepted sequence \(highest).")
            }
            guard sequence >= highest else {
                throw OtaError(code: "downgrade", message: "The manifest's sequence \(sequence) is older than \(highest).")
            }
        }
        if let minNative = minNative, minNative > nativeBuild {
            throw OtaError(
                code: "native_too_old",
                message: "This UI needs app build \(minNative) or later; this is build \(nativeBuild)."
            )
        }
    }

    /// `<directory>/_denext/ota.json` as a JSON object, if present and readable.
    static func readManifest(in directory: URL) -> [String: Any]? {
        let url = directory.appendingPathComponent(manifestPath, isDirectory: false)
        guard let data = try? Data(contentsOf: url) else { return nil }
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    /// `path` inside `directory`, or nil when it would resolve outside it.
    static func file(_ path: String, in directory: URL) -> URL? {
        guard isSafeRelativePath(path) else { return nil }
        let target = directory.appendingPathComponent(path, isDirectory: false)
        let base = directory.standardizedFileURL.path
        return target.standardizedFileURL.path.hasPrefix(base.hasSuffix("/") ? base : base + "/") ? target : nil
    }

    func versionDirectory(_ version: String) -> URL {
        return root.appendingPathComponent(version, isDirectory: true)
    }

    private func hasVersion(_ version: String) -> Bool {
        return fileManager.fileExists(atPath: versionDirectory(version).appendingPathComponent("index.html").path)
    }

    // MARK: Launch

    /// Called before the bridge loads the first page. Returns the directory to serve (nil:
    /// the bundled UI) and whether this launch is a pending version's trial, which the caller
    /// guards with the watchdog. The first call in a process is the launch; a later one (a
    /// second bridge view controller) keeps serving the active UI instead of counting again.
    func prepareLaunch() -> (directory: URL?, trial: Bool) {
        if launchPrepared {
            if let pending = pending, hasVersion(pending) { return (versionDirectory(pending), true) }
            if let current = current, hasVersion(current) { return (versionDirectory(current), false) }
            return (nil, false)
        }
        launchPrepared = true
        // A new app binary brings its own bundled UI (and maybe new native code), so a UI
        // downloaded for the old binary is dropped, as Capacitor drops its own deploy path. The
        // bundled UI's version is part of the key, so a rebuild that ships a different UI
        // counts as a new binary even when its version and build numbers were not bumped.
        let binaryVersion = [
            Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "",
            Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "",
            bundledVersion ?? ""
        ].joined(separator: "+")
        if defaults.string(forKey: Key.binaryVersion) != binaryVersion {
            reset()
            defaults.set(binaryVersion, forKey: Key.binaryVersion)
            return (nil, false)
        }
        if let pending = pending {
            if hasVersion(pending) && trialAttempts < DenextOtaStore.maxTrialAttempts {
                // One more try: the app died before this version confirmed its boot, which may
                // not be the version's fault (the OS kills backgrounded apps).
                trialAttempts += 1
                return (versionDirectory(pending), true)
            }
            // Out of tries (or the files are gone): roll back before loading.
            CAPLog.print("denext OTA: UI \(pending) never confirmed its boot; rolling back.")
            return (rollBackPending(), false)
        }
        if let current = current {
            if hasVersion(current) {
                return (versionDirectory(current), false)
            }
            self.current = nil
        }
        return (nil, false)
    }

    // MARK: Transitions

    /// Records a verified `version` as staged (and its `sequence` as accepted), deleting the
    /// directory of the version it replaces unless that one is current, pending or bundled.
    func stage(_ version: String, sequence: Int64?) {
        if let old = stagedVersion, old != version, old != current, old != pending, old != bundledVersion {
            try? fileManager.removeItem(at: versionDirectory(old))
        }
        stagedVersion = version
        if let sequence = sequence, sequence > (highestSequence ?? -1) {
            defaults.set(NSNumber(value: sequence), forKey: Key.sequence)
        }
    }

    /// `activate` / `apply`: `version` (the staged one) starts its trial, which counts as its
    /// first attempt; nothing stays staged.
    func beginTrial(_ version: String) {
        previous = current
        pending = version
        trialAttempts = 1
        defaults.removeObject(forKey: Key.legacyTrialStarted)
        stagedVersion = nil
    }

    /// `booted`: the pending version becomes current, and every other version is deleted
    /// (bar a staged one).
    func confirmPending() {
        guard let pending = pending else { return }
        current = pending
        self.pending = nil
        previous = nil
        clearTrial()
        prune(keeping: [pending, stagedVersion].compactMap { $0 })
    }

    /// Drops the pending version (remembered as rejected) and returns the directory to serve:
    /// the previous version if it is still there, otherwise nil for the bundled UI.
    func rollBackPending() -> URL? {
        let target = previous.flatMap { hasVersion($0) ? $0 : nil }
        if let failed = pending {
            rejected = failed
            try? fileManager.removeItem(at: versionDirectory(failed))
        }
        pending = nil
        previous = nil
        clearTrial()
        current = target
        return target.map(versionDirectory)
    }

    /// Back to the bundled UI with no downloaded or staged versions and nothing rejected. The
    /// accepted `sequence` is kept: downgrade protection outlives a reset.
    func reset() {
        for key in [Key.current, Key.pending, Key.previous, Key.legacyTrialStarted, Key.trialAttempts, Key.rejected, Key.staged] {
            defaults.removeObject(forKey: key)
        }
        try? fileManager.removeItem(at: root)
    }

    private func clearTrial() {
        defaults.removeObject(forKey: Key.trialAttempts)
        defaults.removeObject(forKey: Key.legacyTrialStarted)
    }

    private func prune(keeping versions: [String]) {
        guard let entries = try? fileManager.contentsOfDirectory(at: root, includingPropertiesForKeys: nil) else {
            return
        }
        for entry in entries where !versions.contains(entry.lastPathComponent) {
            try? fileManager.removeItem(at: entry)
        }
    }

    // MARK: Download

    /// A UI already on the device that files can be copied from, with its manifest's
    /// SHA-256 → path index.
    private struct LocalSource {
        let directory: URL
        let pathsBySha: [String: String]
    }

    /// The running download (if any), then the bundled UI.
    private func localSources() -> [LocalSource] {
        var directories: [URL] = []
        if let current = current, hasVersion(current) { directories.append(versionDirectory(current)) }
        if let bundled = DenextOtaStore.bundledDirectory { directories.append(bundled) }
        return directories.map { directory in
            var index: [String: String] = [:]
            for case let file as [String: Any] in (DenextOtaStore.readManifest(in: directory)?["files"] as? [Any]) ?? [] {
                if let sha = file["sha256"] as? String, let path = file["path"] as? String, index[sha] == nil {
                    index[sha] = path
                }
            }
            return LocalSource(directory: directory, pathsBySha: index)
        }
    }

    /// Creates the versions directory, excluded from device backups (a UI is re-downloadable).
    private func ensureRoot() throws {
        try fileManager.createDirectory(at: root, withIntermediateDirectories: true)
        var url = root
        var values = URLResourceValues()
        values.isExcludedFromBackup = true
        try? url.setResourceValues(values)
    }

    /// Deletes the `.partial` / `.tmp` directories of other versions: only the version being
    /// downloaded may resume from an earlier attempt.
    private func removeStaleAttempts(except version: String) {
        guard let entries = try? fileManager.contentsOfDirectory(at: root, includingPropertiesForKeys: nil) else {
            return
        }
        for entry in entries where entry.pathExtension == "partial" || entry.pathExtension == "tmp" {
            if entry.deletingPathExtension().lastPathComponent != version {
                try? fileManager.removeItem(at: entry)
            }
        }
    }

    /// Off the main thread. Fetches and verifies every file into `<version>.partial/` (copying
    /// the ones a UI on the device already has, and keeping the ones an interrupted attempt
    /// already verified there), writes the manifest next to them, then renames the directory to
    /// `<version>/`. A failure keeps the verified files for the next attempt. Each file streams
    /// to disk while it is hashed and is refused as soon as it outgrows its manifest `size`.
    func download(_ request: ApplyRequest) async throws -> DownloadStats {
        try ensureRoot()
        removeStaleAttempts(except: request.version)
        let partial = root.appendingPathComponent("\(request.version).partial", isDirectory: true)
        let scratch = root.appendingPathComponent("\(request.version).tmp", isDirectory: true)
        let destination = versionDirectory(request.version)
        try fileManager.createDirectory(at: partial, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: scratch, withIntermediateDirectories: true)
        let sources = localSources()
        let downloader = DenextOtaDownloader(baseUrl: request.baseUrl, headers: request.headers)
        defer { downloader.invalidate() }

        let stats = try await withThrowingTaskGroup(of: Bool.self, returning: DownloadStats.self) { group in
            var stats = DownloadStats()
            var remaining = request.files.makeIterator()
            for _ in 0..<DenextOtaStore.maxConcurrentDownloads {
                guard let file = remaining.next() else { break }
                group.addTask {
                    try await self.fetchFile(file, downloader: downloader, sources: sources, into: partial, scratch: scratch)
                }
            }
            while let copied = try await group.next() {
                if copied { stats.copied += 1 } else { stats.downloaded += 1 }
                if let file = remaining.next() {
                    group.addTask {
                        try await self.fetchFile(file, downloader: downloader, sources: sources, into: partial, scratch: scratch)
                    }
                }
            }
            return stats
        }
        try Task.checkCancellation()
        try writeManifest(request, into: partial)
        try? fileManager.removeItem(at: destination)
        try fileManager.moveItem(at: partial, to: destination)
        try? fileManager.removeItem(at: scratch)
        return stats
    }

    /// The version's own `_denext/ota.json`, so a later update can copy files from it and the
    /// page can read its own version (`otaBooted`).
    private func writeManifest(_ request: ApplyRequest, into directory: URL) throws {
        let files = request.files.map { ["path": $0.path, "sha256": $0.sha256, "size": $0.size] as [String: Any] }
        let data = try JSONSerialization.data(withJSONObject: ["version": request.version, "files": files])
        let target = directory.appendingPathComponent(DenextOtaStore.manifestPath, isDirectory: false)
        try fileManager.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: target, options: .atomic)
    }

    /// Puts one verified file at its path in `directory`; returns true when it was already
    /// there from an earlier attempt or copied from the device, false when it was downloaded.
    private func fetchFile(
        _ file: ManifestFile,
        downloader: DenextOtaDownloader,
        sources: [LocalSource],
        into directory: URL,
        scratch: URL
    ) async throws -> Bool {
        try Task.checkCancellation()
        guard let target = DenextOtaStore.file(file.path, in: directory) else {
            throw OtaError(code: "invalid", message: "\(file.path) leaves the UI directory.")
        }
        if DenextOtaStore.digest(of: target, limit: file.size).map({ $0 == (file.sha256, file.size) }) == true {
            return true
        }
        let temp = scratch.appendingPathComponent(UUID().uuidString, isDirectory: false)
        defer { try? fileManager.removeItem(at: temp) }
        let copied = copyLocal(file, from: sources, to: temp)
        if !copied {
            try await downloader.fetch(file, to: temp)
        }
        try fileManager.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try? fileManager.removeItem(at: target)
        try fileManager.moveItem(at: temp, to: target)
        return copied
    }

    /// Copies `file` into `temp` from a UI already on the device that has a file with the same
    /// SHA-256 (by its manifest, or at the same path), verifying the bytes as they stream.
    private func copyLocal(_ file: ManifestFile, from sources: [LocalSource], to temp: URL) -> Bool {
        for source in sources {
            var candidates: [String] = []
            if let path = source.pathsBySha[file.sha256] { candidates.append(path) }
            if !candidates.contains(file.path) { candidates.append(file.path) }
            for candidate in candidates {
                guard let url = DenextOtaStore.file(candidate, in: source.directory) else { continue }
                if DenextOtaStore.copyVerified(from: url, to: temp, file: file) { return true }
            }
        }
        return false
    }

    /// The SHA-256 and size of the file at `url`, read in chunks; nil when it is missing,
    /// unreadable or longer than `limit` bytes.
    static func digest(of url: URL, limit: Int64) -> (String, Int64)? {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return nil }
        defer { try? handle.close() }
        var hasher = SHA256()
        var size: Int64 = 0
        do {
            while let chunk = try handle.read(upToCount: 65_536), !chunk.isEmpty {
                size += Int64(chunk.count)
                if size > limit { return nil }
                hasher.update(data: chunk)
            }
        } catch {
            return nil
        }
        return (hex(hasher.finalize()), size)
    }

    /// Streams `source` into a new file at `target` while hashing it; true when the bytes match
    /// `file` (a mismatch deletes `target`).
    static func copyVerified(from source: URL, to target: URL, file: ManifestFile) -> Bool {
        guard let input = try? FileHandle(forReadingFrom: source) else { return false }
        defer { try? input.close() }
        guard FileManager.default.createFile(atPath: target.path, contents: nil),
              let output = try? FileHandle(forWritingTo: target) else { return false }
        var hasher = SHA256()
        var size: Int64 = 0
        var ok = true
        do {
            while let chunk = try input.read(upToCount: 65_536), !chunk.isEmpty {
                size += Int64(chunk.count)
                if size > file.size { ok = false; break }
                hasher.update(data: chunk)
                try output.write(contentsOf: chunk)
            }
        } catch {
            ok = false
        }
        try? output.close()
        ok = ok && size == file.size && hex(hasher.finalize()) == file.sha256
        if !ok { try? FileManager.default.removeItem(at: target) }
        return ok
    }
}

/// The network half of `DenextOtaStore.download`: one ephemeral URLSession whose delegate
/// streams each response into a file while hashing it, refuses a response larger than the
/// manifest's size as soon as it gets there, enforces a per-file deadline that grows with the
/// file's size, and follows redirects only within the base URL's origin (the headers, which may
/// carry a bearer token, never reach another origin).
final class DenextOtaDownloader: NSObject, URLSessionDataDelegate, @unchecked Sendable {
    /// One file in flight. Only touched under `lock`.
    private final class Transfer {
        let file: DenextOtaStore.ManifestFile
        let output: FileHandle
        let continuation: CheckedContinuation<Void, Error>
        var hasher = SHA256()
        var received: Int64 = 0
        var failure: DenextOtaStore.OtaError?

        init(file: DenextOtaStore.ManifestFile, output: FileHandle, continuation: CheckedContinuation<Void, Error>) {
            self.file = file
            self.output = output
            self.continuation = continuation
        }
    }

    private let baseUrl: URL
    private let headers: [String: String]
    private let lock = NSLock()
    private var transfers: [Int: Transfer] = [:]
    private var session: URLSession?

    init(baseUrl: URL, headers: [String: String]) {
        self.baseUrl = baseUrl
        self.headers = headers
        super.init()
        let configuration = URLSessionConfiguration.ephemeral
        configuration.timeoutIntervalForRequest = DenextOtaStore.idleTimeout
        configuration.requestCachePolicy = .reloadIgnoringLocalCacheData
        configuration.httpMaximumConnectionsPerHost = DenextOtaStore.maxConcurrentDownloads
        let queue = OperationQueue()
        queue.maxConcurrentOperationCount = 1
        session = URLSession(configuration: configuration, delegate: self, delegateQueue: queue)
    }

    /// Cancels anything still in flight and releases the session (which retains its delegate).
    func invalidate() {
        session?.invalidateAndCancel()
        session = nil
    }

    /// Whether `url` has the base URL's scheme, host and port.
    private func isSameOrigin(_ url: URL?) -> Bool {
        guard let url = url else { return false }
        let port = { (u: URL) -> Int? in u.port ?? (u.scheme?.lowercased() == "https" ? 443 : 80) }
        return url.scheme?.lowercased() == baseUrl.scheme?.lowercased()
            && url.host?.lowercased() == baseUrl.host?.lowercased()
            && port(url) == port(baseUrl)
    }

    /// Downloads `file` into a new file at `destination`, verified against the manifest.
    func fetch(_ file: DenextOtaStore.ManifestFile, to destination: URL) async throws {
        var url = baseUrl
        for segment in DenextOtaStore.segments(file.path) {
            url.appendPathComponent(segment)
        }
        var request = URLRequest(url: url, timeoutInterval: DenextOtaStore.idleTimeout)
        for (name, value) in headers {
            request.setValue(value, forHTTPHeaderField: name)
        }
        guard let session = session,
              FileManager.default.createFile(atPath: destination.path, contents: nil),
              let output = try? FileHandle(forWritingTo: destination) else {
            throw DenextOtaStore.OtaError(code: "download", message: "Could not start downloading \(file.path).")
        }
        let task = session.dataTask(with: request)
        let deadline = DispatchWorkItem { [weak self] in
            self?.fail(task.taskIdentifier, DenextOtaStore.OtaError(
                code: "download",
                message: "Downloading \(file.path) took longer than \(Int(DenextOtaStore.fileDeadline(size: file.size))) s."
            ), cancelling: task)
        }
        defer { deadline.cancel() }
        try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
                lock.lock()
                transfers[task.taskIdentifier] = Transfer(file: file, output: output, continuation: continuation)
                lock.unlock()
                DispatchQueue.global().asyncAfter(deadline: .now() + DenextOtaStore.fileDeadline(size: file.size), execute: deadline)
                task.resume()
            }
        } onCancel: {
            task.cancel()
        }
    }

    /// Records `failure` for the transfer (the first one wins) and cancels its task.
    private func fail(_ id: Int, _ failure: DenextOtaStore.OtaError, cancelling task: URLSessionTask) {
        lock.lock()
        if let transfer = transfers[id], transfer.failure == nil { transfer.failure = failure }
        lock.unlock()
        task.cancel()
    }

    private func transfer(_ id: Int) -> Transfer? {
        lock.lock()
        defer { lock.unlock() }
        return transfers[id]
    }

    func urlSession(
        _ session: URLSession,
        dataTask: URLSessionDataTask,
        didReceive response: URLResponse,
        completionHandler: @escaping @Sendable (URLSession.ResponseDisposition) -> Void
    ) {
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard let transfer = transfer(dataTask.taskIdentifier) else { return completionHandler(.cancel) }
        if status != 200 {
            fail(dataTask.taskIdentifier, DenextOtaStore.OtaError(
                code: "download",
                message: "Downloading \(transfer.file.path) failed with HTTP \(status)."
            ), cancelling: dataTask)
            return completionHandler(.cancel)
        }
        if response.expectedContentLength > transfer.file.size {
            fail(dataTask.taskIdentifier, DenextOtaStore.OtaError(
                code: "integrity",
                message: "\(transfer.file.path) is larger than the manifest says."
            ), cancelling: dataTask)
            return completionHandler(.cancel)
        }
        completionHandler(.allow)
    }

    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data) {
        guard let transfer = transfer(dataTask.taskIdentifier), transfer.failure == nil else { return }
        transfer.received += Int64(data.count)
        guard transfer.received <= transfer.file.size else {
            return fail(dataTask.taskIdentifier, DenextOtaStore.OtaError(
                code: "integrity",
                message: "\(transfer.file.path) is larger than the manifest says."
            ), cancelling: dataTask)
        }
        transfer.hasher.update(data: data)
        do {
            try transfer.output.write(contentsOf: data)
        } catch {
            fail(dataTask.taskIdentifier, DenextOtaStore.OtaError(
                code: "download",
                message: "Could not write \(transfer.file.path): \(error.localizedDescription)"
            ), cancelling: dataTask)
        }
    }

    func urlSession(
        _ session: URLSession,
        task: URLSessionTask,
        willPerformHTTPRedirection response: HTTPURLResponse,
        newRequest request: URLRequest,
        completionHandler: @escaping @Sendable (URLRequest?) -> Void
    ) {
        guard isSameOrigin(request.url) else {
            fail(task.taskIdentifier, DenextOtaStore.OtaError(
                code: "download",
                message: "Refusing a redirect to another origin (\(request.url?.host ?? "?"))."
            ), cancelling: task)
            return completionHandler(nil)
        }
        var next = request
        for (name, value) in headers {
            next.setValue(value, forHTTPHeaderField: name)
        }
        completionHandler(next)
    }

    func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
        lock.lock()
        let transfer = transfers.removeValue(forKey: task.taskIdentifier)
        lock.unlock()
        guard let transfer = transfer else { return }
        try? transfer.output.close()
        let file = transfer.file
        if let failure = transfer.failure {
            transfer.continuation.resume(throwing: failure)
        } else if let error = error {
            let cancelled = (error as? URLError)?.code == .cancelled
            transfer.continuation.resume(throwing: cancelled ? CancellationError() as Error : DenextOtaStore.OtaError(
                code: "download",
                message: "Downloading \(file.path) failed: \(error.localizedDescription)"
            ))
        } else if transfer.received != file.size || DenextOtaStore.hex(transfer.hasher.finalize()) != file.sha256 {
            transfer.continuation.resume(throwing: DenextOtaStore.OtaError(
                code: "integrity",
                message: "\(file.path) does not match the manifest."
            ))
        } else {
            transfer.continuation.resume()
        }
    }
}
