// denext-ota-template: 4 sha256=6f3ed1b78024a6b280bbb729bd0f51d4c53fee818c2b82e36a72d1a0132d348f
// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota` after upgrading denext (then ship a new binary). See
// https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import Foundation
import UIKit

/// The native side of denext's over-the-air UI updates, reached from the web app as
/// `window.Capacitor.Plugins.DenextOta` (`checkForUiUpdate`, `otaBooted`, `otaStatus` and
/// `otaReset` from `denext/mobile`). `DenextBridgeViewController` registers it before the
/// first page loads.
///
/// - `status() → { current, bundled, pending, rejected, staged }`
/// - `download({ baseUrl, headers, manifest }) → { version, downloaded, copied, staged }`: downloads
///   and verifies the version and records it as staged, WITHOUT switching to it (`staged: false`
///   when the version is already running); rejects with code `invalid`, `busy`, `rejected`,
///   `download`, `integrity`, `signature`, `insecure`, `downgrade`, `native_too_old` or
///   `native_mismatch` (all but `busy`, `rejected`, `download` and a file's `integrity` before
///   any download: see
///   `DenextOtaStore.ApplyRequest`)
/// - `activate({ version }) → { version }`: switches to the staged version (its trial launch);
///   rejects with code `invalid`, `busy`, `not_staged` or `rejected`
/// - `apply({ baseUrl, headers, manifest }) → { version, downloaded, copied, switched }`: `download`
///   then `activate` in one call, with `download`'s rejections (`switched: false` when the version
///   is already running)
/// - `booted({ version? }) → { confirmed }`: confirms the UI on its trial launch, which cancels
///   the rollback watchdog, when `version` (the page's own UI version) is that UI; a call from
///   another page is ignored
/// - `reset()`: back to the bundled UI; during a download it cancels the download first
///
/// Only `activate` and `apply` switch versions: a staged version is never started on its own.
@objc(DenextOtaPlugin)
public class DenextOtaPlugin: CAPPlugin, CAPBridgedPlugin, @unchecked Sendable {
    public let identifier = "DenextOtaPlugin"
    public let jsName = "DenextOta"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "status", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "download", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "activate", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "apply", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "booted", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "reset", returnType: CAPPluginReturnPromise)
    ]

    /// Main-thread only. Set while `download` or `apply` downloads, so a second one cannot race it.
    private var applying = false
    /// Main-thread only. The download in flight, cancelled by `reset` or the apply deadline.
    private var downloadTask: Task<Void, Never>?
    /// Main-thread only. Cancels the download in flight after `DenextOtaStore.applyDeadline`.
    private var applyDeadline: DispatchWorkItem?
    /// Main-thread only. Set when the apply deadline cancelled the download.
    private var deadlineExpired = false
    /// Main-thread only. `reset` calls waiting for the download in flight to stop.
    private var pendingResets: [CAPPluginCall] = []
    /// Main-thread only. Rolls a UI on its trial launch back unless `booted` cancels it.
    private var watchdog: DispatchWorkItem?
    /// Main-thread only. When the armed watchdog fires.
    private var watchdogDeadline: Date?
    /// Main-thread only. The watchdog time left while the app is inactive (the watchdog paused).
    private var watchdogRemaining: TimeInterval?
    private var observers: [NSObjectProtocol] = []

    override public func load() {
        // The trial's clock runs only while the app is in the foreground: a user who switches
        // away during the trial launch does not get a good UI rolled back.
        let center = NotificationCenter.default
        observers = [
            center.addObserver(forName: UIApplication.willResignActiveNotification, object: nil, queue: .main) { [weak self] _ in
                self?.pauseWatchdog()
            },
            center.addObserver(forName: UIApplication.didBecomeActiveNotification, object: nil, queue: .main) { [weak self] _ in
                self?.resumeWatchdog()
            }
        ]
    }

    deinit {
        observers.forEach(NotificationCenter.default.removeObserver)
    }

    @objc func status(_ call: CAPPluginCall) {
        DispatchQueue.main.async {
            let store = DenextOtaStore.shared
            call.resolve([
                "current": store.current ?? NSNull(),
                "bundled": store.bundledVersion ?? NSNull(),
                "pending": store.pending ?? NSNull(),
                "rejected": store.rejected ?? NSNull(),
                "staged": store.staged ?? NSNull()
            ])
        }
    }

    /// Fetches every manifest file into `<version>.partial/` (copying the ones already on
    /// the device), verifies each SHA-256 and size, renames the directory to `<version>/` and
    /// records it as staged. The running UI is untouched: only `activate` switches to it.
    @objc func download(_ call: CAPPluginCall) {
        guard let request = parseRequest(call) else { return }
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            let store = DenextOtaStore.shared
            guard !self.rejectIfBusy(call) else { return }
            if request.version == store.current {
                // Already running: nothing to download, and nothing to stage.
                call.resolve(["version": request.version, "downloaded": 0, "copied": 0, "staged": false])
                return
            }
            guard !self.rejectIfRejected(call, request.version) else { return }
            self.stage(request, call: call) { stats in
                call.resolve([
                    "version": request.version,
                    "downloaded": stats.downloaded,
                    "copied": stats.copied,
                    "staged": true
                ])
            }
        }
    }

    /// Switches to the staged version: records it as pending (its trial launch), switches the
    /// webview to it (which reloads the page) and arms the watchdog, exactly as `apply` does
    /// after its download.
    @objc func activate(_ call: CAPPluginCall) {
        guard let version = call.getString("version"), DenextOtaStore.isSha256(version) else {
            call.reject("version must be a UI version.", "invalid")
            return
        }
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            guard !self.rejectIfBusy(call) else { return }
            guard DenextOtaStore.shared.staged == version else {
                call.reject("UI \(version) is not staged; download it first.", "not_staged")
                return
            }
            guard !self.rejectIfRejected(call, version) else { return }
            self.startTrial(version, resolving: call, with: ["version": version])
        }
    }

    /// Fetches every manifest file into `<version>.partial/` (copying the ones already on
    /// the device), verifies each SHA-256 and size, renames the directory to `<version>/`,
    /// records it as pending, and switches the webview to it (which reloads the page). The
    /// reload is the version's trial launch: `booted` from the new page confirms it,
    /// otherwise the watchdog rolls it back.
    @objc func apply(_ call: CAPPluginCall) {
        guard let request = parseRequest(call) else { return }
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            let store = DenextOtaStore.shared
            guard !self.rejectIfBusy(call) else { return }
            if request.version == store.current {
                call.resolve(["version": request.version, "downloaded": 0, "copied": 0, "switched": false])
                return
            }
            guard !self.rejectIfRejected(call, request.version) else { return }
            self.stage(request, call: call) { stats in
                self.startTrial(request.version, resolving: call, with: [
                    "version": request.version,
                    "downloaded": stats.downloaded,
                    "copied": stats.copied,
                    "switched": true
                ])
            }
        }
    }

    /// The request `download` and `apply` take, or nil after rejecting `call` with its code.
    private func parseRequest(_ call: CAPPluginCall) -> DenextOtaStore.ApplyRequest? {
        do {
            return try DenextOtaStore.ApplyRequest(
                baseUrl: call.getString("baseUrl"),
                headers: call.getObject("headers"),
                manifest: call.getObject("manifest")
            )
        } catch {
            call.reject(error.localizedDescription, (error as? DenextOtaStore.OtaError)?.code ?? "invalid")
            return nil
        }
    }

    /// Main thread. Rejects `call` with `busy` while a download or a trial launch is in
    /// progress; returns whether it did.
    private func rejectIfBusy(_ call: CAPPluginCall) -> Bool {
        guard applying || DenextOtaStore.shared.pending != nil else { return false }
        call.reject("A UI update is already in progress.", "busy")
        return true
    }

    /// Main thread. Rejects `call` with `rejected` when `version` was rolled back on this
    /// device; returns whether it did.
    private func rejectIfRejected(_ call: CAPPluginCall, _ version: String) -> Bool {
        guard version == DenextOtaStore.shared.rejected else { return false }
        call.reject("UI \(version) was rolled back on this device.", "rejected")
        return true
    }

    /// Main thread. Downloads and verifies `request` into its version directory and records it
    /// as staged, then calls `completion` on the main thread (with zero stats when that version
    /// is already staged). A failure, a `reset` or the apply deadline rejects `call` instead.
    private func stage(
        _ request: DenextOtaStore.ApplyRequest,
        call: CAPPluginCall,
        completion: @escaping @Sendable (DenextOtaStore.DownloadStats) -> Void
    ) {
        let store = DenextOtaStore.shared
        if store.staged == request.version {
            completion(DenextOtaStore.DownloadStats())
            return
        }
        applying = true
        deadlineExpired = false
        downloadTask = Task {
            let result: Result<DenextOtaStore.DownloadStats, Error>
            do {
                result = .success(try await store.download(request))
            } catch {
                result = .failure(error)
            }
            DispatchQueue.main.async {
                self.finishStage(request, call: call, result: result, completion: completion)
            }
        }
        let deadline = DispatchWorkItem { [weak self] in
            self?.deadlineExpired = true
            self?.downloadTask?.cancel()
        }
        applyDeadline = deadline
        DispatchQueue.main.asyncAfter(deadline: .now() + DenextOtaStore.applyDeadline, execute: deadline)
    }

    /// Main thread. Settles `stage`: records the staged version, or rejects `call`, and runs any
    /// `reset` that waited for the download.
    private func finishStage(
        _ request: DenextOtaStore.ApplyRequest,
        call: CAPPluginCall,
        result: Result<DenextOtaStore.DownloadStats, Error>,
        completion: (DenextOtaStore.DownloadStats) -> Void
    ) {
        applying = false
        downloadTask = nil
        applyDeadline?.cancel()
        applyDeadline = nil
        if !pendingResets.isEmpty {
            call.reject("The UI update was cancelled by a reset.", "download")
            let resets = pendingResets
            pendingResets = []
            performReset(resets)
            return
        }
        switch result {
        case .success(let stats):
            DenextOtaStore.shared.stage(request.version, sequence: request.sequence)
            completion(stats)
        case .failure(let error):
            if deadlineExpired {
                call.reject("The UI update took longer than \(Int(DenextOtaStore.applyDeadline / 60)) minutes.", "download")
            } else if let error = error as? DenextOtaStore.OtaError {
                call.reject(error.message, error.code)
            } else if error is CancellationError {
                call.reject("The UI download was cancelled.", "download")
            } else {
                call.reject(error.localizedDescription, "download")
            }
        }
    }

    /// Main thread. Starts the staged `version`'s trial: records it as pending (clearing
    /// staged), resolves `call`, switches the webview to it and arms the watchdog.
    private func startTrial(_ version: String, resolving call: CAPPluginCall, with result: [String: Any]) {
        let store = DenextOtaStore.shared
        store.beginTrial(version)
        call.resolve(result)
        switchWebView(to: store.versionDirectory(version))
        armWatchdog()
    }

    @objc func booted(_ call: CAPPluginCall) {
        let version = call.getString("version")
        DispatchQueue.main.async { [weak self] in
            let store = DenextOtaStore.shared
            // A page names its own UI version: a late call from the page being replaced (or any
            // page other than the one on trial) confirms nothing. A caller that names none (a web
            // side older than this check) is taken at its word.
            guard let pending = store.pending, version == nil || version == pending else {
                call.resolve(["confirmed": false])
                return
            }
            self?.cancelWatchdog()
            store.confirmPending()
            call.resolve(["confirmed": true])
        }
    }

    @objc func reset(_ call: CAPPluginCall) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            if self.applying {
                // Stop the download first; the reset runs once it has (see finishStage).
                self.pendingResets.append(call)
                self.downloadTask?.cancel()
                return
            }
            self.performReset([call])
        }
    }

    /// Main thread. Back to the bundled UI, resolving `calls`.
    private func performReset(_ calls: [CAPPluginCall]) {
        cancelWatchdog()
        DenextOtaStore.shared.reset()
        calls.forEach { $0.resolve() }
        switchWebView(to: nil)
    }

    /// Main thread. Called for a trial launch (`DenextBridgeViewController`) and after
    /// `activate` / `apply`: arms the watchdog for the full boot timeout.
    func armWatchdog() {
        startWatchdog(seconds: DenextOtaStore.bootTimeout)
    }

    /// Main thread. Arms the watchdog to fire in `seconds`.
    private func startWatchdog(seconds: TimeInterval) {
        watchdog?.cancel()
        watchdogRemaining = nil
        let item = DispatchWorkItem { [weak self] in
            self?.watchdogFired()
        }
        watchdog = item
        watchdogDeadline = Date().addingTimeInterval(seconds)
        DispatchQueue.main.asyncAfter(deadline: .now() + seconds, execute: item)
    }

    /// Main thread. The trial UI did not confirm in time: roll it back.
    private func watchdogFired() {
        watchdog = nil
        watchdogDeadline = nil
        let store = DenextOtaStore.shared
        guard let failed = store.pending else { return }
        CAPLog.print("denext OTA: UI \(failed) did not confirm its boot; rolling back.")
        switchWebView(to: store.rollBackPending())
    }

    /// Main thread. The app is going inactive: stop the watchdog's clock.
    private func pauseWatchdog() {
        guard let item = watchdog, let deadline = watchdogDeadline else { return }
        item.cancel()
        watchdog = nil
        watchdogDeadline = nil
        watchdogRemaining = max(1, deadline.timeIntervalSinceNow)
    }

    /// Main thread. The app is active again: restart the watchdog with the time it had left.
    private func resumeWatchdog() {
        guard let remaining = watchdogRemaining else { return }
        watchdogRemaining = nil
        guard DenextOtaStore.shared.pending != nil else { return }
        startWatchdog(seconds: remaining)
    }

    /// Main thread.
    private func cancelWatchdog() {
        watchdog?.cancel()
        watchdog = nil
        watchdogDeadline = nil
        watchdogRemaining = nil
    }

    /// Main thread. Points the asset handler at `directory` (nil: the bundled UI) and reloads.
    /// `CAPBridgeViewController.setServerBasePath(path:)` is `CapacitorBridge.setServerBasePath(_:)`
    /// followed by a reload of the start URL.
    private func switchWebView(to directory: URL?) {
        guard let path = (directory ?? DenextOtaStore.bundledDirectory)?.path else { return }
        MainActor.assumeIsolated {
            if let viewController = bridge?.viewController as? CAPBridgeViewController {
                viewController.setServerBasePath(path: path)
            } else {
                bridge?.setServerBasePath(path)
            }
        }
    }
}
