// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota --force` to update it. See https://denext.dev/docs/desktop.

import Capacitor
import Foundation

/// The native side of denext's over-the-air UI updates, reached from the web app as
/// `window.Capacitor.Plugins.DenextOta` (`checkForUiUpdate`, `otaBooted`, `otaStatus` and
/// `otaReset` from `denext/mobile`). `DenextBridgeViewController` registers it before the
/// first page loads.
///
/// - `status() → { current, bundled, pending, rejected, staged }`
/// - `download({ baseUrl, headers, manifest }) → { version, downloaded, copied }`: downloads and
///   verifies the version and records it as staged, WITHOUT switching to it; rejects with code
///   `invalid`, `busy`, `rejected`, `download` or `integrity`
/// - `activate({ version }) → { version }`: switches to the staged version (its trial launch);
///   rejects with code `invalid`, `busy`, `not_staged` or `rejected`
/// - `apply({ baseUrl, headers, manifest }) → { version, downloaded, copied }`: `download` then
///   `activate` in one call, with `download`'s rejections
/// - `booted()`: confirms the UI on its trial launch, which cancels the rollback watchdog
/// - `reset()`: back to the bundled UI (rejects with `busy` during a download)
///
/// Only `activate` and `apply` switch versions: a staged version is never started on its own.
@objc(DenextOtaPlugin)
public class DenextOtaPlugin: CAPPlugin, CAPBridgedPlugin {
    public let identifier = "DenextOtaPlugin"
    public let jsName = "DenextOta"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "status", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "download", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "activate", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "apply", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "booted", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "reset", returnType: CAPPluginReturnPromise)
    ]

    /// Main-thread only. Set while `download` or `apply` downloads, so a second one cannot race it.
    private var applying = false
    /// Main-thread only. Rolls a UI on its trial launch back unless `booted` cancels it.
    private var watchdog: DispatchWorkItem?

    @objc func status(_ call: CAPPluginCall) {
        DispatchQueue.main.async {
            let store = DenextOtaStore.shared
            call.resolve([
                "current": store.current ?? NSNull(),
                "bundled": store.bundledVersion ?? NSNull(),
                "pending": store.pending ?? NSNull(),
                "rejected": store.rejected ?? NSNull(),
                "staged": store.staged ?? NSNull()
            ])
        }
    }

    /// Fetches every manifest file into `<version>.partial/` (copying the ones already on
    /// the device), verifies each SHA-256 and size, renames the directory to `<version>/` and
    /// records it as staged. The running UI is untouched: only `activate` switches to it.
    @objc func download(_ call: CAPPluginCall) {
        guard let request = parseRequest(call) else { return }
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            let store = DenextOtaStore.shared
            guard !self.rejectIfBusy(call) else { return }
            if request.version == store.current {
                // Already running: nothing to download, and nothing to stage.
                call.resolve(["version": request.version, "downloaded": 0, "copied": 0])
                return
            }
            guard !self.rejectIfRejected(call, request.version) else { return }
            self.stage(request, call: call) { stats in
                call.resolve([
                    "version": request.version,
                    "downloaded": stats.downloaded,
                    "copied": stats.copied
                ])
            }
        }
    }

    /// Switches to the staged version: records it as pending (its trial launch), switches the
    /// webview to it (which reloads the page) and arms the watchdog, exactly as `apply` does
    /// after its download.
    @objc func activate(_ call: CAPPluginCall) {
        guard let version = call.getString("version"), DenextOtaStore.isSha256(version) else {
            call.reject("version must be a UI version.", "invalid")
            return
        }
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            guard !self.rejectIfBusy(call) else { return }
            guard DenextOtaStore.shared.staged == version else {
                call.reject("UI \(version) is not staged; download it first.", "not_staged")
                return
            }
            guard !self.rejectIfRejected(call, version) else { return }
            self.startTrial(version, resolving: call, with: ["version": version])
        }
    }

    /// Fetches every manifest file into `<version>.partial/` (copying the ones already on
    /// the device), verifies each SHA-256 and size, renames the directory to `<version>/`,
    /// records it as pending, and switches the webview to it (which reloads the page). The
    /// reload is the version's trial launch: `booted` from the new page confirms it,
    /// otherwise the watchdog rolls it back.
    @objc func apply(_ call: CAPPluginCall) {
        guard let request = parseRequest(call) else { return }
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            let store = DenextOtaStore.shared
            guard !self.rejectIfBusy(call) else { return }
            if request.version == store.current {
                call.resolve(["version": request.version, "downloaded": 0, "copied": 0])
                return
            }
            guard !self.rejectIfRejected(call, request.version) else { return }
            self.stage(request, call: call) { stats in
                self.startTrial(request.version, resolving: call, with: [
                    "version": request.version,
                    "downloaded": stats.downloaded,
                    "copied": stats.copied
                ])
            }
        }
    }

    /// The request `download` and `apply` take, or nil after rejecting `call` with `invalid`.
    private func parseRequest(_ call: CAPPluginCall) -> DenextOtaStore.ApplyRequest? {
        do {
            return try DenextOtaStore.ApplyRequest(
                baseUrl: call.getString("baseUrl"),
                headers: call.getObject("headers"),
                manifest: call.getObject("manifest")
            )
        } catch {
            call.reject(error.localizedDescription, (error as? DenextOtaStore.OtaError)?.code ?? "invalid")
            return nil
        }
    }

    /// Main thread. Rejects `call` with `busy` while a download or a trial launch is in
    /// progress; returns whether it did.
    private func rejectIfBusy(_ call: CAPPluginCall) -> Bool {
        guard applying || DenextOtaStore.shared.pending != nil else { return false }
        call.reject("A UI update is already in progress.", "busy")
        return true
    }

    /// Main thread. Rejects `call` with `rejected` when `version` was rolled back on this
    /// device; returns whether it did.
    private func rejectIfRejected(_ call: CAPPluginCall, _ version: String) -> Bool {
        guard version == DenextOtaStore.shared.rejected else { return false }
        call.reject("UI \(version) was rolled back on this device.", "rejected")
        return true
    }

    /// Main thread. Downloads and verifies `request` into its version directory and records it
    /// as staged, then calls `completion` on the main thread (with zero stats when that version
    /// is already staged). A failure rejects `call` instead.
    private func stage(
        _ request: DenextOtaStore.ApplyRequest,
        call: CAPPluginCall,
        completion: @escaping (DenextOtaStore.DownloadStats) -> Void
    ) {
        let store = DenextOtaStore.shared
        if store.staged == request.version {
            completion(DenextOtaStore.DownloadStats())
            return
        }
        applying = true
        Task {
            do {
                let stats = try await store.download(request)
                await MainActor.run {
                    self.applying = false
                    store.stage(request.version)
                    completion(stats)
                }
            } catch {
                await MainActor.run {
                    self.applying = false
                    let code = (error as? DenextOtaStore.OtaError)?.code ?? "download"
                    call.reject(error.localizedDescription, code)
                }
            }
        }
    }

    /// Main thread. Starts the staged `version`'s trial: records it as pending (clearing
    /// staged), resolves `call`, switches the webview to it and arms the watchdog.
    private func startTrial(_ version: String, resolving call: CAPPluginCall, with result: [String: Any]) {
        let store = DenextOtaStore.shared
        store.beginTrial(version)
        call.resolve(result)
        switchWebView(to: store.versionDirectory(version))
        armWatchdog()
    }

    @objc func booted(_ call: CAPPluginCall) {
        DispatchQueue.main.async { [weak self] in
            self?.watchdog?.cancel()
            self?.watchdog = nil
            DenextOtaStore.shared.confirmPending()
            call.resolve()
        }
    }

    @objc func reset(_ call: CAPPluginCall) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            guard !self.applying else {
                call.reject("A UI update is in progress.", "busy")
                return
            }
            self.watchdog?.cancel()
            self.watchdog = nil
            DenextOtaStore.shared.reset()
            call.resolve()
            self.switchWebView(to: nil)
        }
    }

    /// Main thread. Called for a trial launch (`DenextBridgeViewController`) and after
    /// `activate` / `apply`.
    func armWatchdog() {
        watchdog?.cancel()
        let item = DispatchWorkItem { [weak self] in
            guard let self = self else { return }
            self.watchdog = nil
            let store = DenextOtaStore.shared
            guard let failed = store.pending else { return }
            CAPLog.print("denext OTA: UI \(failed) did not confirm its boot; rolling back.")
            self.switchWebView(to: store.rollBackPending())
        }
        watchdog = item
        DispatchQueue.main.asyncAfter(deadline: .now() + DenextOtaStore.watchdogSeconds, execute: item)
    }

    /// Main thread. Points the asset handler at `directory` (nil: the bundled UI) and reloads.
    /// `CAPBridgeViewController.setServerBasePath(path:)` is `CapacitorBridge.setServerBasePath(_:)`
    /// followed by a reload of the start URL.
    private func switchWebView(to directory: URL?) {
        guard let path = (directory ?? DenextOtaStore.bundledDirectory)?.path else { return }
        if let viewController = bridge?.viewController as? CAPBridgeViewController {
            viewController.setServerBasePath(path: path)
        } else {
            bridge?.setServerBasePath(path)
        }
    }
}
