// denext-ota-template: 9 sha256=267dd1f83df00e4a80d58a0c4c234be49b005e63c1fde3d85272772d3cbf72e0
// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota` after upgrading denext (then ship a new binary). See
// https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import UIKit
import WebKit

/// A `CAPBridgeViewController` that serves the over-the-air UI (see `DenextOtaStore`). Its
/// router (`DenextOtaRouter`) serves a downloaded UI's files only while they match the UI's
/// signed manifest.
///
/// Use it where the app would use `CAPBridgeViewController`: `Main.storyboard`'s view
/// controller class and `SceneDelegate`'s root view controller (`denext mobile add-ota`
/// sets both when they still name `CAPBridgeViewController`). An app with its own bridge
/// subclass changes that subclass's superclass to `DenextBridgeViewController` and calls
/// `super` from any `instanceDescriptor()` / `capacitorDidLoad()` override.
///
/// `CAPBridgeViewController.loadView()` calls `instanceDescriptor()` first, before the bridge
/// exists, then creates the bridge (which injects Capacitor's JS as document-start scripts)
/// and calls `capacitorDidLoad()`; the page itself loads later, from `viewDidLoad()`. So the
/// start directory is chosen, and the `DenextOta` plugin registered, before the first page.
///
/// A web content process that terminates is reloaded by Capacitor's own navigation delegate
/// (`loadView()` is final, so this class cannot replace it). If that reload leaves a trial UI
/// blank, the watchdog rolls it back.
class DenextBridgeViewController: CAPBridgeViewController {
    /// Serves an exported multi-page app's routes: Capacitor's router answers every path
    /// without an extension with the root `index.html` (a single-page-app assumption), so
    /// `/protected` would load the home page.
    override open func router() -> Router {
        DenextOtaRouter()
    }

    /// Whether this launch serves a downloaded UI on its trial launch.
    private var otaTrialLaunch = false

    /// Picks which UI directory the app starts from (a confirmed or trial over-the-air UI,
    /// else the bundled `public/`), rolling back a trial the app died in before the page loads.
    override func instanceDescriptor() -> InstanceDescriptor {
        let descriptor = super.instanceDescriptor()
        let launch = DenextOtaStore.shared.prepareLaunch()
        if let directory = launch.directory {
            descriptor.appLocation = directory
        }
        otaTrialLaunch = launch.trial
        return descriptor
    }

    override func capacitorDidLoad() {
        super.capacitorDidLoad()
        // denext: native plugin calls are accepted from the app's main frame only.
        DenextMainFrameBridgeGuard.install(on: bridge)
        // denext: the OS's low-memory warning reaches the page (AppState's memoryWarning).
        DenextMemoryWarning.install(on: bridge)
        let plugin = DenextOtaPlugin()
        bridge?.registerPluginInstance(plugin)
        // denext auth sessions: openAuthSession() in denext/mobile.
        bridge?.registerPluginInstance(DenextAuthSessionPlugin())
        if otaTrialLaunch {
            plugin.armWatchdog()
        }
    }
}

/// Forwards the OS's low-memory warning to the page as the "denext:memorywarning" window
/// event, which React Native mode's AppState emits as "memoryWarning".
@MainActor
enum DenextMemoryWarning {
    /// The notification observer (one per process: a recreated bridge replaces it).
    private static var observer: NSObjectProtocol?

    /// Observes UIApplication.didReceiveMemoryWarningNotification for the bridge's page. Call
    /// it from capacitorDidLoad().
    static func install(on bridge: CAPBridgeProtocol?) {
        if let observer { NotificationCenter.default.removeObserver(observer) }
        observer = NotificationCenter.default.addObserver(
            forName: UIApplication.didReceiveMemoryWarningNotification,
            object: nil,
            queue: .main
        ) { [weak bridge] _ in
            MainActor.assumeIsolated {
                bridge?.triggerWindowJSEvent(eventName: "denext:memorywarning")
            }
        }
    }
}

/// Drops native bridge calls that do not come from the app's main frame.
///
/// WebKit delivers the bridge script message from every frame of the page, and Capacitor's
/// handler does not check which frame sent it, so an iframe (an embedded site, an ad, a widget)
/// could call any installed plugin. Capacitor injects its JS bridge into the main frame only,
/// so a message from another frame is never the app's own. This handler takes Capacitor's place
/// under the same name and forwards main-frame messages to it unchanged.
@MainActor
final class DenextMainFrameBridgeGuard: NSObject, WKScriptMessageHandler {
    /// The name Capacitor registers its handler under (WebViewDelegationHandler.handlerName).
    private static let handlerName = "bridge"
    /// Capacitor's own handler, which the bridge owns.
    private weak var target: WKScriptMessageHandler?
    /// The frame origins already logged, so a looping frame cannot flood the log.
    private var logged = Set<String>()

    private init(target: WKScriptMessageHandler) {
        self.target = target
    }

    /// Puts the guard in front of Capacitor's bridge handler. Call it from capacitorDidLoad(),
    /// which runs before the first page loads.
    static func install(on bridge: CAPBridgeProtocol?) {
        guard let bridge = bridge as? CapacitorBridge else {
            NSLog("[denext] could not guard the native bridge: the bridge is not a CapacitorBridge")
            return
        }
        let handler = bridge.webViewDelegationHandler
        let controller = handler.contentController
        controller.removeScriptMessageHandler(forName: handlerName)
        controller.add(DenextMainFrameBridgeGuard(target: handler), name: handlerName)
    }

    func userContentController(
        _ userContentController: WKUserContentController,
        didReceive message: WKScriptMessage
    ) {
        guard message.frameInfo.isMainFrame else {
            let origin = message.frameInfo.securityOrigin
            let from = origin.host.isEmpty ? origin.protocol : "\(origin.protocol)://\(origin.host)"
            if logged.count < 16, logged.insert(from).inserted {
                NSLog("[denext] refused a native plugin call from a non-main frame (%@)", from)
            }
            return
        }
        target?.userContentController(userContentController, didReceive: message)
    }
}

/// `/route` → `/route/index.html` or `/route.html` when the export has that page, else the root
/// `index.html` (a single-page app's client routes keep working). `basePath` is the directory
/// the UI is served from (the bundled `public/` or an over-the-air UI), set by Capacitor.
/// `path` arrives decoded (`/%2e%2e%2fsecret` is `/../secret`), so a path that leaves that
/// directory is refused: a navigation gets the root `index.html`, anything else the directory
/// itself, which the asset handler cannot read (the request fails).
struct DenextExportRouter: Router {
    var basePath: String = ""
    func route(for path: String) -> String {
        let url = URL(fileURLWithPath: path)
        guard staysInside(path) else {
            return basePath + (url.pathExtension.isEmpty ? "/index.html" : "/")
        }
        guard url.pathExtension.isEmpty else { return basePath + path }
        let trimmed = path.hasSuffix("/") ? String(path.dropLast()) : path
        if !trimmed.isEmpty {
            let fm = FileManager.default
            for candidate in [trimmed + "/index.html", trimmed + ".html"] {
                if fm.fileExists(atPath: basePath + candidate) { return basePath + candidate }
            }
        }
        return basePath + "/index.html"
    }

    /// Whether `path` names a file under `basePath`: no `..` segment, and once standardized
    /// the path is `basePath` or below it.
    private func staysInside(_ path: String) -> Bool {
        if path.split(separator: "/").contains("..") { return false }
        let root = URL(fileURLWithPath: basePath.isEmpty ? "/" : basePath).standardizedFileURL.path
        let resolved = URL(fileURLWithPath: basePath + path).standardizedFileURL.path
        return resolved == root || resolved.hasPrefix(root.hasSuffix("/") ? root : root + "/")
    }
}
