// denext-ota-template: 4 sha256=953b861a475bd84b7e8a1939bc3a55d6c5ff0c80eeb43c9c118c779f13a615ae
// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota` after upgrading denext (then ship a new binary). See
// https://denext.dev/docs/desktop.

@preconcurrency import Capacitor
import UIKit

/// A `CAPBridgeViewController` that serves the over-the-air UI (see `DenextOtaStore`).
///
/// Use it where the app would use `CAPBridgeViewController`: `Main.storyboard`'s view
/// controller class and `SceneDelegate`'s root view controller (`denext mobile add-ota`
/// sets both when they still name `CAPBridgeViewController`). An app with its own bridge
/// subclass changes that subclass's superclass to `DenextBridgeViewController` and calls
/// `super` from any `instanceDescriptor()` / `capacitorDidLoad()` override.
///
/// `CAPBridgeViewController.loadView()` calls `instanceDescriptor()` first, before the bridge
/// exists, then creates the bridge (which injects Capacitor's JS as document-start scripts)
/// and calls `capacitorDidLoad()`; the page itself loads later, from `viewDidLoad()`. So the
/// start directory is chosen, and the `DenextOta` plugin registered, before the first page.
///
/// A web content process that terminates is reloaded by Capacitor's own navigation delegate
/// (`loadView()` is final, so this class cannot replace it). If that reload leaves a trial UI
/// blank, the watchdog rolls it back.
class DenextBridgeViewController: CAPBridgeViewController {
    /// Whether this launch serves a downloaded UI on its trial launch.
    private var otaTrialLaunch = false

    /// Picks which UI directory the app starts from (a confirmed or trial over-the-air UI,
    /// else the bundled `public/`), rolling back a trial the app died in before the page loads.
    override func instanceDescriptor() -> InstanceDescriptor {
        let descriptor = super.instanceDescriptor()
        let launch = DenextOtaStore.shared.prepareLaunch()
        if let directory = launch.directory {
            descriptor.appLocation = directory
        }
        otaTrialLaunch = launch.trial
        return descriptor
    }

    override func capacitorDidLoad() {
        super.capacitorDidLoad()
        let plugin = DenextOtaPlugin()
        bridge?.registerPluginInstance(plugin)
        // denext auth sessions: openAuthSession() in denext/mobile.
        bridge?.registerPluginInstance(DenextAuthSessionPlugin())
        if otaTrialLaunch {
            plugin.armWatchdog()
        }
    }
}
