// denext-auth-session-template: 1 sha256=68320a7cf7c46c2d72e04358b8b01a2485a6157ce545ecf75695a29eb78d1988
// Generated by `denext mobile add auth-session` (denext auth sessions). Safe to commit;
// re-run it after upgrading denext (then ship a new binary). See https://denext.dev/docs/desktop.

import AuthenticationServices
@preconcurrency import Capacitor
import Foundation
import UIKit

/// The native side of `openAuthSession()` from `denext/mobile`, reached from the web app as
/// `window.Capacitor.Plugins.DenextAuthSession`. `DenextBridgeViewController` registers it.
///
/// - `start({ url, callbackScheme, preferEphemeral }) → { url }`: opens `url` in an
///   `ASWebAuthenticationSession` sheet and resolves with the full callback URL once the page
///   navigates to `<callbackScheme>:`. Rejects with code `cancelled` (the user closed the
///   sheet, or `cancel` ran), `busy` (a session is already open), `invalid` (`url` is not
///   absolute https, or `callbackScheme` is not a custom scheme) or `unsupported` (the sheet
///   could not be presented).
/// - `cancel()`: closes the open sheet; its `start` rejects with `cancelled`.
///
/// The callback scheme needs no Info.plist registration: the session catches the redirect
/// itself, so it never reaches the app's URL handling. PKCE and `state` are the web app's job.
@objc(DenextAuthSessionPlugin)
public class DenextAuthSessionPlugin: CAPPlugin, CAPBridgedPlugin,
    ASWebAuthenticationPresentationContextProviding, @unchecked Sendable {
    public let identifier = "DenextAuthSessionPlugin"
    public let jsName = "DenextAuthSession"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "start", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "cancel", returnType: CAPPluginReturnPromise)
    ]

    /// Schemes that are not an app's own (the web, the OS, Capacitor's webview origin).
    private static let reservedSchemes: Set<String> = [
        "http", "https", "file", "content", "javascript", "data", "blob", "about", "mailto",
        "tel", "sms", "intent", "capacitor"
    ]

    /// Main-thread only. The open session, held strongly until it completes: nothing else
    /// retains it, and a released session closes its sheet.
    private var session: ASWebAuthenticationSession?
    /// Main-thread only. The `start` call the open session answers.
    private var pendingCall: CAPPluginCall?
    /// Main-thread only. Bumped per session, so a late completion of an old one is ignored.
    private var generation = 0

    @objc func start(_ call: CAPPluginCall) {
        guard let raw = call.getString("url"), let url = URL(string: raw),
              url.scheme?.lowercased() == "https", let host = url.host, !host.isEmpty else {
            call.reject("url must be an absolute https URL", "invalid")
            return
        }
        guard let scheme = call.getString("callbackScheme"), Self.isCustomScheme(scheme) else {
            call.reject("callbackScheme must be a custom URL scheme such as myapp", "invalid")
            return
        }
        let ephemeral = call.getBool("preferEphemeral") ?? false
        DispatchQueue.main.async {
            self.begin(call, url: url, scheme: scheme, ephemeral: ephemeral)
        }
    }

    @objc func cancel(_ call: CAPPluginCall) {
        DispatchQueue.main.async {
            let open = self.session
            let pending = self.pendingCall
            self.session = nil
            self.pendingCall = nil
            self.generation += 1
            open?.cancel()
            pending?.reject("the auth session was cancelled", "cancelled")
            call.resolve()
        }
    }

    public func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
        // The session starts on the main thread, and asks from there.
        return bridge?.webView?.window ?? bridge?.viewController?.view.window ?? ASPresentationAnchor()
    }

    /// Main thread. Opens the sheet unless one is already open.
    private func begin(_ call: CAPPluginCall, url: URL, scheme: String, ephemeral: Bool) {
        if session != nil {
            call.reject("an auth session is already open", "busy")
            return
        }
        generation += 1
        let token = generation
        let session = ASWebAuthenticationSession(url: url, callbackURLScheme: scheme) { [weak self] callbackURL, error in
            DispatchQueue.main.async {
                self?.complete(token: token, callbackURL: callbackURL, error: error)
            }
        }
        session.presentationContextProvider = self
        session.prefersEphemeralWebBrowserSession = ephemeral
        self.session = session
        pendingCall = call
        if !session.start() {
            self.session = nil
            pendingCall = nil
            generation += 1
            call.reject("the sign-in sheet could not be presented", "unsupported")
        }
    }

    /// Main thread. Settles the `start` call of session `token`, if it is still the open one.
    private func complete(token: Int, callbackURL: URL?, error: Error?) {
        guard token == generation, let call = pendingCall else { return }
        session = nil
        pendingCall = nil
        if let callbackURL {
            call.resolve(["url": callbackURL.absoluteString])
            return
        }
        if let authError = error as? ASWebAuthenticationSessionError, authError.code == .canceledLogin {
            call.reject("the user closed the sign-in sheet", "cancelled")
            return
        }
        call.reject(error?.localizedDescription ?? "the auth session ended without a callback", "unsupported")
    }

    /// A lower-case custom scheme: a letter, then letters, digits, `+`, `-` or `.`.
    private static func isCustomScheme(_ scheme: String) -> Bool {
        return scheme.range(of: "^[a-z][a-z0-9+.-]*$", options: .regularExpression) != nil
            && !reservedSchemes.contains(scheme)
    }
}
