// generated by `denext migrate` — safe to edit; re-running may overwrite
import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.brainwires.t3code.rnweb",
  appName: "T3 RN Web",
  // denext's static export (`deno task export`) writes here; Capacitor bundles it.
  webDir: "out",
  // The Capacitor shell lives beside Expo’s own native folders (/ios and /android are
  // `expo prebuild` output, git-ignored): it is committed, so a Mac builds it without `cap add`.
  ios: { path: "capacitor-ios" },
};

export default config;
