// generated by `denext migrate` — safe to edit; re-running may overwrite
import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.brainwires.t3code.rnweb",
  appName: "T3 RN Web",
  // denext's static export (`deno task export`) writes here; Capacitor bundles it.
  webDir: "out",
};

export default config;
