// generated by `denext migrate` — safe to edit; re-running may overwrite
// RN-on-denext (branch rn-on-denext): T3 Code's Expo app built from the same source by denext's
// React Native mode into a Capacitor shell. Run `deno task web:prepare` first (denext-web/).
import type { DenextConfig } from "denext/server";
import extraThemes from "./generated-uniwind-theme-names.json" with { type: "json" };

/** The app config the expo-* shims read (Constants.expoConfig); updates off, as in RN Bench. */
const expoConfig = {
  name: "T3 Code",
  slug: "t3-code",
  version: "2.0.0",
  owner: "pingdotgg",
  orientation: "portrait",
  userInterfaceStyle: "automatic",
  extra: { appVariant: "production", eas: { projectId: "d763fcb8-d37c-41ea-a773-b54a0ab4a454" } },
};

/** DM Sans, which the expo-font config plugin embeds natively (copied by web:prepare). */
const fonts = [
  ["DMSans-Regular", "DMSans_400Regular"],
  ["DMSans-Medium", "DMSans_500Medium"],
  ["DMSans-Bold", "DMSans_700Bold"],
]
  .map(
    ([family, file]) =>
      `@font-face{font-family:"${family}";src:url("/fonts/${file}.ttf") format("truetype");font-display:block}`,
  )
  .join("");

export default {
  mode: "spa",
  compatibilityMode: true,
  // uniwind: the extraThemes metro.config.js passes to withUniwindConfig.
  reactNative: { uniwind: { extraThemes } },
  // The Tailwind (uniwind) input, metro.config.js's cssEntryFile; App.tsx imports global.css.
  tailwind: { input: "./global.css", output: "./global.gen.css" },
  spa: {
    entry: "./index.ts",
    title: "T3 Code",
    head:
      `<script>globalThis.__DENEXT_EXPO_CONFIG__=${JSON.stringify(expoConfig)}</script>` +
      `<style>${fonts}</style>`,
    // The Capacitor shell loads files as they are: no .gz siblings.
    precompress: false,
  },
} satisfies DenextConfig;
