// denext-ota-template: 9 sha256=53ed5910402e95f7c56a2145753eaf4344fedfdae883fe8b170f3f0d9a36bfc2
// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota` after upgrading denext (then ship a new binary). See
// https://denext.dev/docs/desktop.

package dev.denext.ota;

import android.content.Context;
import com.getcapacitor.Bridge;
import com.getcapacitor.ServerPath;
import java.io.File;

/**
 * Wires denext's over-the-air UI into a Capacitor {@code BridgeActivity}. Call it from
 * {@code MainActivity.onCreate} BEFORE {@code super.onCreate}, which builds the bridge:
 *
 * <pre>{@code
 * public class MainActivity extends BridgeActivity {
 *     @Override
 *     protected void onCreate(Bundle savedInstanceState) {
 *         DenextOta.prepare(this, bridgeBuilder);
 *         super.onCreate(savedInstanceState);
 *     }
 * }
 * }</pre>
 *
 * It registers {@link DenextOtaPlugin} and points the bridge at the UI to start from: a
 * confirmed or trial over-the-air UI, else the bundled {@code public/}. A trial the app died
 * in twice is rolled back here, before the first page loads, and a downloaded UI whose stored
 * manifest no longer verifies is quarantined. It also gives the bridge the route processor that
 * checks each file of a downloaded UI against that manifest before the local server reads it (an
 * app that sets its own {@code RouteProcessor} replaces it, and with it that check).
 * {@code bridgeBuilder} is the activity's own protected field, which is why the activity passes
 * it in.
 *
 * <p>A WebView renderer that dies is recovered by the {@code MainActivity} denext composes: it
 * recreates the activity in the same process, which calls this again and keeps the same UI (a
 * launch's trial attempt is counted once per process). A renderer that dies three times within a
 * minute ends the app instead, and the next launch counts that as a failed trial attempt.
 */
public final class DenextOta {

    private DenextOta() {}

    /**
     * Registers the plugin and picks the start directory.
     *
     * @param context the activity (any context of the app works)
     * @param bridgeBuilder the activity's {@code bridgeBuilder}
     */
    public static void prepare(Context context, Bridge.Builder bridgeBuilder) {
        bridgeBuilder.addPlugin(DenextOtaPlugin.class);
        DenextOtaStore store = DenextOtaStore.get(context);
        // Every file the local server reads from a downloaded UI is checked against its signed
        // manifest first (DenextOtaStore.Routes).
        bridgeBuilder.setRouteProcessor(store.routes());
        File directory = store.startDirectory();
        if (directory != null) {
            bridgeBuilder.setServerPath(new ServerPath(ServerPath.PathType.BASE_PATH, directory.getAbsolutePath()));
        }
    }
}
