// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota --force` to update it. See https://denext.dev/docs/desktop.

package dev.denext.ota;

import android.net.Uri;
import android.os.Handler;
import android.os.Looper;
import androidx.annotation.Nullable;
import com.getcapacitor.JSObject;
import com.getcapacitor.Logger;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * The native side of denext's over-the-air UI updates, reached from the web app as
 * {@code window.Capacitor.Plugins.DenextOta} ({@code checkForUiUpdate}, {@code otaBooted},
 * {@code otaStatus} and {@code otaReset} from {@code denext/mobile}). {@link DenextOta#prepare}
 * registers it. See {@link DenextOtaStore} for the files and state.
 *
 * <ul>
 *   <li>{@code status() → { current, bundled, pending, rejected, staged }}
 *   <li>{@code download({ baseUrl, headers, manifest }) → { version, downloaded, copied }}:
 *       downloads and verifies the version and records it as staged, WITHOUT switching to it;
 *       rejects with code {@code invalid}, {@code busy}, {@code rejected}, {@code download},
 *       {@code integrity}, {@code signature} or {@code insecure} (the last two, and a version that
 *       does not match the files, before any download: see {@link DenextOtaStore#checkTrust})
 *   <li>{@code activate({ version }) → { version }}: switches to the staged version (its trial
 *       launch); rejects with code {@code invalid}, {@code busy}, {@code not_staged} or
 *       {@code rejected}
 *   <li>{@code apply({ baseUrl, headers, manifest }) → { version, downloaded, copied }}:
 *       {@code download} then {@code activate} in one call, with {@code download}'s rejections
 *   <li>{@code booted()}: confirms the UI on its trial launch, cancelling the watchdog
 *   <li>{@code reset()}: back to the bundled UI (rejects with {@code busy} during a download)
 * </ul>
 *
 * <p>Only {@code activate} and {@code apply} switch versions: a staged version is never started
 * on its own.
 */
@CapacitorPlugin(name = "DenextOta")
public class DenextOtaPlugin extends Plugin {

    private final Handler mainHandler = new Handler(Looper.getMainLooper());
    private final ExecutorService downloads = Executors.newSingleThreadExecutor();
    /** Main-thread only. Set while download or apply downloads, so a second one cannot race it. */
    private boolean applying = false;
    /** Main-thread only. Rolls a UI on its trial launch back unless booted cancels it. */
    @Nullable
    private Runnable watchdog;

    private DenextOtaStore store() {
        return DenextOtaStore.get(getContext());
    }

    @Override
    public void load() {
        if (DenextOtaStore.launchIsTrial) {
            mainHandler.post(this::armWatchdog);
        }
    }

    @Override
    protected void handleOnDestroy() {
        downloads.shutdownNow();
    }

    @PluginMethod
    public void status(PluginCall call) {
        DenextOtaStore store = store();
        JSObject result = new JSObject();
        result.put("current", orNull(store.current()));
        result.put("bundled", orNull(store.bundledVersion()));
        result.put("pending", orNull(store.pending()));
        result.put("rejected", orNull(store.rejected()));
        result.put("staged", orNull(store.staged()));
        call.resolve(result);
    }

    /**
     * Fetches every manifest file into {@code <version>.partial/} (copying the ones already on
     * the device), verifies each SHA-256 and size, renames the directory to {@code <version>/}
     * and records it as staged. The running UI is untouched: only activate switches to it.
     */
    @PluginMethod
    public void download(PluginCall call) {
        final DenextOtaStore.ApplyRequest request;
        try {
            request = parseApplyRequest(call, store());
        } catch (DenextOtaStore.OtaException ex) {
            call.reject(ex.getMessage(), ex.code);
            return;
        }
        mainHandler.post(() -> {
            DenextOtaStore store = store();
            if (rejectIfBusy(call, store)) {
                return;
            }
            if (request.version.equals(store.current())) {
                // Already running: nothing to download, and nothing to stage.
                call.resolve(result(request.version, new DenextOtaStore.DownloadStats()));
                return;
            }
            if (rejectIfRejected(call, store, request.version)) {
                return;
            }
            stage(store, request, call, (stats) -> call.resolve(result(request.version, stats)));
        });
    }

    /**
     * Switches to the staged version: records it as pending (its trial launch), switches the
     * webview to it (which reloads the page) and arms the watchdog, exactly as apply does after
     * its download.
     */
    @PluginMethod
    public void activate(PluginCall call) {
        final String version = call.getString("version");
        if (!DenextOtaStore.isSha256(version)) {
            call.reject("version must be a UI version.", "invalid");
            return;
        }
        mainHandler.post(() -> {
            DenextOtaStore store = store();
            if (rejectIfBusy(call, store)) {
                return;
            }
            if (!version.equals(store.staged())) {
                call.reject("UI " + version + " is not staged; download it first.", "not_staged");
                return;
            }
            if (rejectIfRejected(call, store, version)) {
                return;
            }
            JSObject result = new JSObject();
            result.put("version", version);
            startTrial(store, version, call, result);
        });
    }

    /**
     * Fetches every manifest file into {@code <version>.partial/} (copying the ones already on
     * the device), verifies each SHA-256 and size, renames the directory to {@code <version>/},
     * records it as pending, and switches the webview to it (which reloads the page). The
     * reload is the version's trial launch: booted from the new page confirms it, otherwise the
     * watchdog rolls it back.
     */
    @PluginMethod
    public void apply(PluginCall call) {
        final DenextOtaStore.ApplyRequest request;
        try {
            request = parseApplyRequest(call, store());
        } catch (DenextOtaStore.OtaException ex) {
            call.reject(ex.getMessage(), ex.code);
            return;
        }
        mainHandler.post(() -> {
            DenextOtaStore store = store();
            if (rejectIfBusy(call, store)) {
                return;
            }
            if (request.version.equals(store.current())) {
                call.resolve(result(request.version, new DenextOtaStore.DownloadStats()));
                return;
            }
            if (rejectIfRejected(call, store, request.version)) {
                return;
            }
            stage(store, request, call, (stats) -> startTrial(store, request.version, call, result(request.version, stats)));
        });
    }

    /** What to do on the main thread once a version is staged. */
    private interface OnStaged {
        void run(DenextOtaStore.DownloadStats stats);
    }

    /** Main thread. Rejects call with busy while a download or a trial launch is in progress; returns whether it did. */
    private boolean rejectIfBusy(PluginCall call, DenextOtaStore store) {
        if (!applying && store.pending() == null) {
            return false;
        }
        call.reject("A UI update is already in progress.", "busy");
        return true;
    }

    /** Rejects call with rejected when version was rolled back on this device; returns whether it did. */
    private static boolean rejectIfRejected(PluginCall call, DenextOtaStore store, String version) {
        if (!version.equals(store.rejected())) {
            return false;
        }
        call.reject("UI " + version + " was rolled back on this device.", "rejected");
        return true;
    }

    /**
     * Main thread. Downloads and verifies request into its version directory and records it as
     * staged, then runs then on the main thread (with zero stats when that version is already
     * staged). A failure rejects call instead.
     */
    private void stage(DenextOtaStore store, DenextOtaStore.ApplyRequest request, PluginCall call, OnStaged then) {
        if (request.version.equals(store.staged())) {
            then.run(new DenextOtaStore.DownloadStats());
            return;
        }
        applying = true;
        downloads.execute(() -> {
            try {
                DenextOtaStore.DownloadStats stats = store.download(request);
                mainHandler.post(() -> {
                    applying = false;
                    store.stage(request.version);
                    then.run(stats);
                });
            } catch (DenextOtaStore.OtaException ex) {
                mainHandler.post(() -> {
                    applying = false;
                    call.reject(ex.getMessage(), ex.code);
                });
            } catch (RuntimeException ex) {
                mainHandler.post(() -> {
                    applying = false;
                    call.reject(String.valueOf(ex), "download");
                });
            }
        });
    }

    /**
     * Main thread. Starts the staged version's trial: records it as pending (clearing staged),
     * resolves call, switches the webview to it and arms the watchdog.
     */
    private void startTrial(DenextOtaStore store, String version, PluginCall call, JSObject result) {
        store.beginTrial(version);
        call.resolve(result);
        switchWebView(store.versionDirectory(version));
        armWatchdog();
    }

    @PluginMethod
    public void booted(PluginCall call) {
        mainHandler.post(() -> {
            cancelWatchdog();
            store().confirmPending();
            call.resolve();
        });
    }

    @PluginMethod
    public void reset(PluginCall call) {
        mainHandler.post(() -> {
            if (applying) {
                call.reject("A UI update is in progress.", "busy");
                return;
            }
            cancelWatchdog();
            store().reset();
            call.resolve();
            switchWebView(null);
        });
    }

    /** Main thread. Called for a trial launch (see load) and after activate / apply. */
    private void armWatchdog() {
        cancelWatchdog();
        watchdog = () -> {
            watchdog = null;
            DenextOtaStore store = store();
            String failed = store.pending();
            if (failed == null) {
                return;
            }
            Logger.warn("denext OTA: UI " + failed + " did not confirm its boot; rolling back.");
            switchWebView(store.rollBackPending());
        };
        mainHandler.postDelayed(watchdog, DenextOtaStore.WATCHDOG_MS);
    }

    private void cancelWatchdog() {
        if (watchdog != null) {
            mainHandler.removeCallbacks(watchdog);
            watchdog = null;
        }
    }

    /** Points the local server at {@code directory} (null: the bundled UI); both calls reload. */
    private void switchWebView(@Nullable File directory) {
        if (directory == null) {
            getBridge().setServerAssetPath(DenextOtaStore.BUNDLED_ASSET_DIR);
        } else {
            getBridge().setServerBasePath(directory.getAbsolutePath());
        }
    }

    private static JSObject result(String version, DenextOtaStore.DownloadStats stats) {
        JSObject result = new JSObject();
        result.put("version", version);
        result.put("downloaded", stats.downloaded);
        result.put("copied", stats.copied);
        return result;
    }

    private static Object orNull(@Nullable String value) {
        return value == null ? JSONObject.NULL : value;
    }

    /**
     * The request download and apply take. Building one is the whole trust check, done before
     * anything is downloaded or any state changes: the file list must hash to the manifest's
     * version (code integrity), and {@link DenextOtaStore#checkTrust} must accept the signature or
     * the transport (codes signature / insecure).
     */
    private static DenextOtaStore.ApplyRequest parseApplyRequest(PluginCall call, DenextOtaStore store)
        throws DenextOtaStore.OtaException {
        String baseUrl = call.getString("baseUrl");
        Uri base = baseUrl == null ? null : Uri.parse(baseUrl);
        if (
            base == null ||
            base.getHost() == null ||
            !("http".equalsIgnoreCase(base.getScheme()) || "https".equalsIgnoreCase(base.getScheme()))
        ) {
            throw new DenextOtaStore.OtaException("invalid", "baseUrl must be an http(s) URL.");
        }
        Map<String, String> headers = new HashMap<>();
        JSObject rawHeaders = call.getObject("headers", new JSObject());
        if (rawHeaders != null) {
            Iterator<String> names = rawHeaders.keys();
            while (names.hasNext()) {
                String name = names.next();
                Object value = rawHeaders.opt(name);
                if (value instanceof String) {
                    headers.put(name, (String) value);
                }
            }
        }
        JSObject manifest = call.getObject("manifest");
        String version = manifest == null ? null : manifest.optString("version", null);
        if (!DenextOtaStore.isSha256(version)) {
            throw new DenextOtaStore.OtaException("invalid", "The manifest is malformed.");
        }
        List<DenextOtaStore.ManifestFile> files = new ArrayList<>();
        Set<String> seen = new HashSet<>();
        try {
            JSONArray rawFiles = manifest.getJSONArray("files");
            for (int index = 0; index < rawFiles.length(); index++) {
                JSONObject file = rawFiles.getJSONObject(index);
                String path = file.getString("path");
                String sha256 = file.getString("sha256");
                long size = file.getLong("size");
                if (
                    !DenextOtaStore.isSafeRelativePath(path) ||
                    path.equals(DenextOtaStore.MANIFEST_PATH) ||
                    !seen.add(path) ||
                    !DenextOtaStore.isSha256(sha256) ||
                    size < 0
                ) {
                    throw new DenextOtaStore.OtaException("invalid", "The manifest lists a malformed file.");
                }
                files.add(new DenextOtaStore.ManifestFile(path, sha256, size));
            }
        } catch (JSONException ex) {
            throw new DenextOtaStore.OtaException("invalid", "The manifest is malformed.");
        }
        if (files.isEmpty()) {
            throw new DenextOtaStore.OtaException("invalid", "The manifest is malformed.");
        }
        if (!seen.contains("index.html")) {
            throw new DenextOtaStore.OtaException("invalid", "The manifest has no index.html.");
        }
        // The version is recomputed from the files, never trusted: files → version → signature.
        if (!DenextOtaStore.manifestVersion(files).equals(version)) {
            throw new DenextOtaStore.OtaException("integrity", "The manifest version does not match its files.");
        }
        Object notes = manifest.opt("notes");
        Object signature = manifest.opt("signature");
        store.checkTrust(
            base,
            version,
            Boolean.TRUE.equals(manifest.opt("required")),
            notes instanceof String ? (String) notes : "",
            signature instanceof String ? (String) signature : null
        );
        return new DenextOtaStore.ApplyRequest(baseUrl, headers, version, files);
    }
}
