// denext-ota-template: 4 sha256=52b314c064e5d4359bd5f95b91beed14c0d9972c3ea5f4fd5c3798ece5c0ee53
// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota` after upgrading denext (then ship a new binary). See
// https://denext.dev/docs/desktop.

package dev.denext.ota;

import android.net.Uri;
import android.os.Handler;
import android.os.Looper;
import android.os.SystemClock;
import androidx.annotation.Nullable;
import com.getcapacitor.JSObject;
import com.getcapacitor.Logger;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.json.JSONObject;

/**
 * The native side of denext's over-the-air UI updates, reached from the web app as
 * {@code window.Capacitor.Plugins.DenextOta} ({@code checkForUiUpdate}, {@code otaBooted},
 * {@code otaStatus} and {@code otaReset} from {@code denext/mobile}). {@link DenextOta#prepare}
 * registers it. See {@link DenextOtaStore} for the files and state.
 *
 * <ul>
 *   <li>{@code status() → { current, bundled, pending, rejected, staged }}
 *   <li>{@code download({ baseUrl, headers, manifest }) → { version, downloaded, copied, staged }}:
 *       downloads and verifies the version and records it as staged, WITHOUT switching to it
 *       ({@code staged: false} when the version is already running); rejects with code
 *       {@code invalid}, {@code busy}, {@code rejected}, {@code download}, {@code integrity},
 *       {@code signature}, {@code insecure}, {@code downgrade}, {@code native_too_old} or
 *       {@code native_mismatch} (the trust and release checks before any download: see
 *       {@link #parseApplyRequest})
 *   <li>{@code activate({ version }) → { version }}: switches to the staged version (its trial
 *       launch); rejects with code {@code invalid}, {@code busy}, {@code not_staged} or
 *       {@code rejected}
 *   <li>{@code apply({ baseUrl, headers, manifest }) → { version, downloaded, copied, switched }}:
 *       {@code download} then {@code activate} in one call, with {@code download}'s rejections
 *       ({@code switched: false} when the version is already running)
 *   <li>{@code booted({ version? }) → { confirmed }}: confirms the UI on its trial launch,
 *       cancelling the watchdog, when {@code version} (the page's own UI version) is that UI; a
 *       call from another page is ignored
 *   <li>{@code reset()}: back to the bundled UI; during a download it cancels the download first
 * </ul>
 *
 * <p>Only {@code activate} and {@code apply} switch versions: a staged version is never started
 * on its own. The trial watchdog counts foreground time only: it pauses in {@code onPause} and
 * resumes with the time left in {@code onResume}.
 */
@CapacitorPlugin(name = "DenextOta")
public class DenextOtaPlugin extends Plugin {

    private final Handler mainHandler = new Handler(Looper.getMainLooper());
    private final ExecutorService downloads = Executors.newSingleThreadExecutor();
    /** Main-thread only. Set while download or apply downloads, so a second one cannot race it. */
    private boolean applying = false;
    /** Main-thread only. Reset calls waiting for the download in flight to stop. */
    private final List<PluginCall> pendingResets = new ArrayList<>();
    /** Main-thread only. Rolls a UI on its trial launch back unless booted cancels it. */
    @Nullable
    private Runnable watchdog;
    /** Main-thread only. When the armed watchdog fires ({@link SystemClock#uptimeMillis}). */
    private long watchdogDeadline = 0;
    /** Main-thread only. The watchdog time left while the app is paused, or -1. */
    private long watchdogRemaining = -1;

    private DenextOtaStore store() {
        return DenextOtaStore.get(getContext());
    }

    @Override
    public void load() {
        if (DenextOtaStore.launchIsTrial) {
            mainHandler.post(this::armWatchdog);
        }
    }

    @Override
    protected void handleOnPause() {
        pauseWatchdog();
    }

    @Override
    protected void handleOnResume() {
        resumeWatchdog();
    }

    @Override
    protected void handleOnDestroy() {
        cancelWatchdog();
        downloads.shutdownNow();
        store().cancelDownload();
    }

    @PluginMethod
    public void status(PluginCall call) {
        DenextOtaStore store = store();
        JSObject result = new JSObject();
        result.put("current", orNull(store.current()));
        result.put("bundled", orNull(store.bundledVersion()));
        result.put("pending", orNull(store.pending()));
        result.put("rejected", orNull(store.rejected()));
        result.put("staged", orNull(store.staged()));
        call.resolve(result);
    }

    /**
     * Fetches every manifest file into {@code <version>.partial/} (copying the ones already on
     * the device), verifies each SHA-256 and size, renames the directory to {@code <version>/}
     * and records it as staged. The running UI is untouched: only activate switches to it.
     */
    @PluginMethod
    public void download(PluginCall call) {
        final DenextOtaStore.ApplyRequest request;
        try {
            request = parseApplyRequest(call, store());
        } catch (DenextOtaStore.OtaException ex) {
            call.reject(ex.getMessage(), ex.code);
            return;
        }
        mainHandler.post(() -> {
            DenextOtaStore store = store();
            if (rejectIfBusy(call, store)) {
                return;
            }
            if (request.version.equals(store.current())) {
                // Already running: nothing to download, and nothing to stage.
                JSObject result = result(request.version, new DenextOtaStore.DownloadStats());
                result.put("staged", false);
                call.resolve(result);
                return;
            }
            if (rejectIfRejected(call, store, request.version)) {
                return;
            }
            stage(store, request, call, (stats) -> {
                JSObject result = result(request.version, stats);
                result.put("staged", true);
                call.resolve(result);
            });
        });
    }

    /**
     * Switches to the staged version: records it as pending (its trial launch), switches the
     * webview to it (which reloads the page) and arms the watchdog, exactly as apply does after
     * its download.
     */
    @PluginMethod
    public void activate(PluginCall call) {
        final String version = call.getString("version");
        if (!DenextOtaStore.isSha256(version)) {
            call.reject("version must be a UI version.", "invalid");
            return;
        }
        mainHandler.post(() -> {
            DenextOtaStore store = store();
            if (rejectIfBusy(call, store)) {
                return;
            }
            if (!version.equals(store.staged())) {
                call.reject("UI " + version + " is not staged; download it first.", "not_staged");
                return;
            }
            if (rejectIfRejected(call, store, version)) {
                return;
            }
            JSObject result = new JSObject();
            result.put("version", version);
            startTrial(store, version, call, result);
        });
    }

    /**
     * Fetches every manifest file into {@code <version>.partial/} (copying the ones already on
     * the device), verifies each SHA-256 and size, renames the directory to {@code <version>/},
     * records it as pending, and switches the webview to it (which reloads the page). The
     * reload is the version's trial launch: booted from the new page confirms it, otherwise the
     * watchdog rolls it back.
     */
    @PluginMethod
    public void apply(PluginCall call) {
        final DenextOtaStore.ApplyRequest request;
        try {
            request = parseApplyRequest(call, store());
        } catch (DenextOtaStore.OtaException ex) {
            call.reject(ex.getMessage(), ex.code);
            return;
        }
        mainHandler.post(() -> {
            DenextOtaStore store = store();
            if (rejectIfBusy(call, store)) {
                return;
            }
            if (request.version.equals(store.current())) {
                JSObject result = result(request.version, new DenextOtaStore.DownloadStats());
                result.put("switched", false);
                call.resolve(result);
                return;
            }
            if (rejectIfRejected(call, store, request.version)) {
                return;
            }
            stage(store, request, call, (stats) -> {
                JSObject result = result(request.version, stats);
                result.put("switched", true);
                startTrial(store, request.version, call, result);
            });
        });
    }

    /** What to do on the main thread once a version is staged. */
    private interface OnStaged {
        void run(DenextOtaStore.DownloadStats stats);
    }

    /** Main thread. Rejects call with busy while a download or a trial launch is in progress; returns whether it did. */
    private boolean rejectIfBusy(PluginCall call, DenextOtaStore store) {
        if (!applying && store.pending() == null) {
            return false;
        }
        call.reject("A UI update is already in progress.", "busy");
        return true;
    }

    /** Rejects call with rejected when version was rolled back on this device; returns whether it did. */
    private static boolean rejectIfRejected(PluginCall call, DenextOtaStore store, String version) {
        if (!version.equals(store.rejected())) {
            return false;
        }
        call.reject("UI " + version + " was rolled back on this device.", "rejected");
        return true;
    }

    /**
     * Main thread. Downloads and verifies request into its version directory and records it as
     * staged, then runs then on the main thread (with zero stats when that version is already
     * staged). A failure or a reset rejects call instead.
     */
    private void stage(DenextOtaStore store, DenextOtaStore.ApplyRequest request, PluginCall call, OnStaged then) {
        if (request.version.equals(store.staged())) {
            then.run(new DenextOtaStore.DownloadStats());
            return;
        }
        applying = true;
        downloads.execute(() -> {
            DenextOtaStore.DownloadStats stats = null;
            DenextOtaStore.OtaException failure = null;
            try {
                stats = store.download(request);
            } catch (DenextOtaStore.OtaException ex) {
                failure = ex;
            } catch (RuntimeException ex) {
                failure = new DenextOtaStore.OtaException("download", String.valueOf(ex));
            }
            final DenextOtaStore.DownloadStats done = stats;
            final DenextOtaStore.OtaException error = failure;
            mainHandler.post(() -> finishStage(store, request, call, done, error, then));
        });
    }

    /** Main thread. Settles stage: records the staged version, or rejects call, and runs any reset that waited. */
    private void finishStage(
        DenextOtaStore store,
        DenextOtaStore.ApplyRequest request,
        PluginCall call,
        @Nullable DenextOtaStore.DownloadStats stats,
        @Nullable DenextOtaStore.OtaException failure,
        OnStaged then
    ) {
        applying = false;
        if (!pendingResets.isEmpty()) {
            call.reject("The UI update was cancelled by a reset.", "download");
            List<PluginCall> resets = new ArrayList<>(pendingResets);
            pendingResets.clear();
            performReset(resets);
            return;
        }
        if (failure != null || stats == null) {
            call.reject(failure == null ? "The UI download failed." : failure.getMessage(), failure == null ? "download" : failure.code);
            return;
        }
        store.stage(request.version, request.sequence);
        then.run(stats);
    }

    /**
     * Main thread. Starts the staged version's trial: records it as pending (clearing staged),
     * resolves call, switches the webview to it and arms the watchdog.
     */
    private void startTrial(DenextOtaStore store, String version, PluginCall call, JSObject result) {
        store.beginTrial(version);
        call.resolve(result);
        switchWebView(store.versionDirectory(version));
        armWatchdog();
    }

    @PluginMethod
    public void booted(PluginCall call) {
        final String version = call.getString("version");
        mainHandler.post(() -> {
            DenextOtaStore store = store();
            String pending = store.pending();
            JSObject result = new JSObject();
            // A page names its own UI version: a late call from the page being replaced (or any
            // page other than the one on trial) confirms nothing. A caller that names none (a web
            // side older than this check) is taken at its word.
            if (pending == null || (version != null && !version.equals(pending))) {
                result.put("confirmed", false);
                call.resolve(result);
                return;
            }
            cancelWatchdog();
            store.confirmPending();
            result.put("confirmed", true);
            call.resolve(result);
        });
    }

    @PluginMethod
    public void reset(PluginCall call) {
        mainHandler.post(() -> {
            if (applying) {
                // Stop the download first; the reset runs once it has (see finishStage).
                pendingResets.add(call);
                store().cancelDownload();
                return;
            }
            List<PluginCall> calls = new ArrayList<>();
            calls.add(call);
            performReset(calls);
        });
    }

    /** Main thread. Back to the bundled UI, resolving calls. */
    private void performReset(List<PluginCall> calls) {
        cancelWatchdog();
        store().reset();
        for (PluginCall call : calls) {
            call.resolve();
        }
        switchWebView(null);
    }

    /** Main thread. Called for a trial launch (see load) and after activate / apply: the full boot timeout. */
    private void armWatchdog() {
        startWatchdog(store().bootTimeoutMs());
    }

    /** Main thread. Arms the watchdog to fire in {@code delayMs}. */
    private void startWatchdog(long delayMs) {
        cancelWatchdog();
        watchdog = () -> {
            watchdog = null;
            DenextOtaStore store = store();
            String failed = store.pending();
            if (failed == null) {
                return;
            }
            Logger.warn("denext OTA: UI " + failed + " did not confirm its boot; rolling back.");
            switchWebView(store.rollBackPending());
        };
        watchdogDeadline = SystemClock.uptimeMillis() + delayMs;
        mainHandler.postAtTime(watchdog, watchdogDeadline);
    }

    /** Main thread. The activity is paused: stop the watchdog's clock. */
    private void pauseWatchdog() {
        if (watchdog == null) {
            return;
        }
        long remaining = Math.max(1_000, watchdogDeadline - SystemClock.uptimeMillis());
        cancelWatchdog();
        watchdogRemaining = remaining;
    }

    /** Main thread. The activity is resumed: restart the watchdog with the time it had left. */
    private void resumeWatchdog() {
        long remaining = watchdogRemaining;
        watchdogRemaining = -1;
        if (remaining > 0 && store().pending() != null) {
            startWatchdog(remaining);
        }
    }

    /** Main thread. */
    private void cancelWatchdog() {
        if (watchdog != null) {
            mainHandler.removeCallbacks(watchdog);
            watchdog = null;
        }
        watchdogRemaining = -1;
    }

    /** Points the local server at {@code directory} (null: the bundled UI); both calls reload. */
    private void switchWebView(@Nullable File directory) {
        if (directory == null) {
            getBridge().setServerAssetPath(DenextOtaStore.BUNDLED_ASSET_DIR);
        } else {
            getBridge().setServerBasePath(directory.getAbsolutePath());
        }
    }

    private static JSObject result(String version, DenextOtaStore.DownloadStats stats) {
        JSObject result = new JSObject();
        result.put("version", version);
        result.put("downloaded", stats.downloaded);
        result.put("copied", stats.copied);
        return result;
    }

    private static Object orNull(@Nullable String value) {
        return value == null ? JSONObject.NULL : value;
    }

    /**
     * The request download and apply take. Building one is the whole trust check, done before
     * anything is downloaded or any state changes: the manifest must be well formed and within the
     * caps (code invalid), the file list must hash to its version (code integrity),
     * {@link DenextOtaStore#checkTrust} must accept the signature or the transport (codes
     * signature / insecure), and {@link DenextOtaStore#checkRelease} its sequence, minNative and
     * nativeFingerprint (codes downgrade / native_too_old / native_mismatch).
     */
    private static DenextOtaStore.ApplyRequest parseApplyRequest(PluginCall call, DenextOtaStore store)
        throws DenextOtaStore.OtaException {
        String baseUrl = call.getString("baseUrl");
        Uri base = baseUrl == null ? null : Uri.parse(baseUrl);
        if (
            base == null ||
            base.getHost() == null ||
            !("http".equalsIgnoreCase(base.getScheme()) || "https".equalsIgnoreCase(base.getScheme()))
        ) {
            throw new DenextOtaStore.OtaException("invalid", "baseUrl must be an http(s) URL.");
        }
        Map<String, String> headers = new HashMap<>();
        JSObject rawHeaders = call.getObject("headers", new JSObject());
        if (rawHeaders != null) {
            Iterator<String> names = rawHeaders.keys();
            while (names.hasNext()) {
                String name = names.next();
                Object value = rawHeaders.opt(name);
                if (value instanceof String) {
                    headers.put(name, (String) value);
                }
            }
        }
        JSObject manifest = call.getObject("manifest");
        String version = manifest == null ? null : manifest.optString("version", null);
        if (manifest == null || !DenextOtaStore.isSha256(version)) {
            throw new DenextOtaStore.OtaException("invalid", "The manifest is malformed.");
        }
        List<DenextOtaStore.ManifestFile> files = DenextOtaStore.parseFiles(manifest.optJSONArray("files"));
        Long sequence = DenextOtaStore.releaseInteger(manifest.opt("sequence"), "sequence");
        Long minNative = DenextOtaStore.releaseInteger(manifest.opt("minNative"), "minNative");
        String nativeFingerprint = DenextOtaStore.fingerprintField(manifest.opt("nativeFingerprint"));
        // The version is recomputed from the files, never trusted: files → version → signature.
        if (!DenextOtaStore.manifestVersion(files).equals(version)) {
            throw new DenextOtaStore.OtaException("integrity", "The manifest version does not match its files.");
        }
        Object notes = manifest.opt("notes");
        Object signature = manifest.opt("signature");
        store.checkTrust(
            base,
            DenextOtaStore.signaturePayload(
                version,
                Boolean.TRUE.equals(manifest.opt("required")),
                notes instanceof String ? (String) notes : "",
                sequence,
                minNative,
                nativeFingerprint
            ),
            signature instanceof String ? (String) signature : null
        );
        store.checkRelease(sequence, minNative, nativeFingerprint);
        return new DenextOtaStore.ApplyRequest(baseUrl, headers, version, files, sequence);
    }
}
