// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota --force` to update it. See https://denext.dev/docs/desktop.

package dev.denext.ota;

import android.content.Context;
import android.content.SharedPreferences;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.net.Uri;
import androidx.annotation.Nullable;
import androidx.core.content.pm.PackageInfoCompat;
import com.getcapacitor.Logger;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * The over-the-air UI's files and state. Versions live in {@code files/denext-ota/<version>/},
 * the state in SharedPreferences:
 *
 * <ul>
 *   <li>{@code current}: the confirmed downloaded version (null: the bundled {@code public/} UI).
 *   <li>{@code pending} / {@code previous}: a version on its trial launch, and what {@code current}
 *       was before it.
 *   <li>{@code trialStarted}: the pending version has been loaded once. Finding it set at launch
 *       means the app died before the UI confirmed its boot, so the version is rolled back unseen.
 *   <li>{@code rejected}: the last version rolled back; {@code apply} refuses it (code
 *       {@code rejected}) until {@code reset}, so a broken server UI cannot put the app in an
 *       apply → rollback loop.
 *   <li>{@code staged}: a version {@code download} verified into its directory, waiting for
 *       {@code activate}. It is never started on its own: launch only ever serves {@code pending}
 *       or {@code current}.
 *   <li>{@code binaryVersion}: the app binary the downloads belong to. A new binary brings its
 *       own bundled UI (and maybe new native code), so every download is dropped.
 * </ul>
 *
 * State transitions are synchronized; {@link #download} runs off the main thread.
 */
final class DenextOtaStore {

    static final long WATCHDOG_MS = 15_000;
    /** The bundled UI's asset directory (Bridge.DEFAULT_WEB_ASSET_DIR). */
    static final String BUNDLED_ASSET_DIR = "public";
    /** The manifest inside a UI directory, as {@code denext export} and {@code denext ota manifest} write it. */
    static final String MANIFEST_PATH = "_denext/ota.json";

    private static final String PREFS = "denext.ota";
    private static final String KEY_CURRENT = "current";
    private static final String KEY_PENDING = "pending";
    private static final String KEY_PREVIOUS = "previous";
    private static final String KEY_TRIAL_STARTED = "trialStarted";
    private static final String KEY_REJECTED = "rejected";
    private static final String KEY_STAGED = "staged";
    private static final String KEY_BINARY_VERSION = "binaryVersion";
    private static final int MAX_CONCURRENT_DOWNLOADS = 6;
    private static final int PER_FILE_TIMEOUT_MS = 30_000;

    private static DenextOtaStore shared;

    /** Set by {@link DenextOta#prepare} when this launch is a pending version's trial; the plugin arms the watchdog. */
    static volatile boolean launchIsTrial = false;

    static synchronized DenextOtaStore get(Context context) {
        if (shared == null) {
            shared = new DenextOtaStore(context.getApplicationContext());
        }
        return shared;
    }

    static final class OtaException extends Exception {

        final String code;

        OtaException(String code, String message) {
            super(message);
            this.code = code;
        }
    }

    static final class ManifestFile {

        final String path;
        final String sha256;
        final long size;

        ManifestFile(String path, String sha256, long size) {
            this.path = path;
            this.sha256 = sha256;
            this.size = size;
        }
    }

    static final class ApplyRequest {

        final String baseUrl;
        final Map<String, String> headers;
        final String version;
        final List<ManifestFile> files;

        ApplyRequest(String baseUrl, Map<String, String> headers, String version, List<ManifestFile> files) {
            this.baseUrl = baseUrl;
            this.headers = headers;
            this.version = version;
            this.files = files;
        }
    }

    /** What {@link #download} did: files fetched over the network, and files copied from the device. */
    static final class DownloadStats {

        int downloaded = 0;
        int copied = 0;
    }

    /** A UI already on the device that files can be copied from. */
    private interface LocalSource {
        /** The bytes at {@code path} inside this UI, or null. {@code path} is already validated. */
        @Nullable
        byte[] read(String path);

        /** SHA-256 → path, from this UI's own manifest. */
        Map<String, String> pathsBySha();
    }

    private final Context context;
    private final SharedPreferences prefs;
    final File root;
    @Nullable
    private String bundledVersion;
    private boolean bundledVersionRead = false;
    private boolean launchPrepared = false;

    private DenextOtaStore(Context context) {
        this.context = context;
        this.prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
        this.root = new File(context.getFilesDir(), "denext-ota");
    }

    static boolean isSha256(@Nullable String value) {
        return value != null && value.matches("[0-9a-f]{64}");
    }

    /** A forward-slash path that stays inside its directory: no empty, "." or ".." segments. */
    static boolean isSafeRelativePath(@Nullable String path) {
        if (path == null || path.isEmpty() || path.contains("\\") || path.indexOf('\0') >= 0) {
            return false;
        }
        for (String segment : path.split("/", -1)) {
            if (segment.isEmpty() || segment.equals(".") || segment.equals("..")) {
                return false;
            }
        }
        return true;
    }

    @Nullable
    synchronized String current() {
        return prefs.getString(KEY_CURRENT, null);
    }

    @Nullable
    synchronized String pending() {
        return prefs.getString(KEY_PENDING, null);
    }

    @Nullable
    synchronized String rejected() {
        return prefs.getString(KEY_REJECTED, null);
    }

    /** The staged version, while its verified directory is still there. */
    @Nullable
    synchronized String staged() {
        String staged = prefs.getString(KEY_STAGED, null);
        return hasVersion(staged) ? staged : null;
    }

    /**
     * Records a verified version as staged, deleting the directory of the version it replaces
     * unless that one is current, pending or bundled.
     */
    synchronized void stage(String version) {
        String old = prefs.getString(KEY_STAGED, null);
        if (
            old != null &&
            !old.equals(version) &&
            !old.equals(prefs.getString(KEY_CURRENT, null)) &&
            !old.equals(prefs.getString(KEY_PENDING, null)) &&
            !old.equals(bundledVersion())
        ) {
            deleteRecursively(versionDirectory(old));
        }
        prefs.edit().putString(KEY_STAGED, version).commit();
    }

    /** The version stamped into the bundled UI ({@code public/_denext/ota.json}), if any. */
    @Nullable
    synchronized String bundledVersion() {
        if (!bundledVersionRead) {
            bundledVersionRead = true;
            JSONObject manifest = parseManifest(readAsset(BUNDLED_ASSET_DIR + "/" + MANIFEST_PATH));
            String version = manifest == null ? null : manifest.optString("version", null);
            bundledVersion = isSha256(version) ? version : null;
        }
        return bundledVersion;
    }

    File versionDirectory(String version) {
        return new File(root, version);
    }

    private boolean hasVersion(@Nullable String version) {
        return version != null && new File(versionDirectory(version), "index.html").isFile();
    }

    /**
     * The directory {@link DenextOta#prepare} starts the bridge from. The first call in a process
     * is the launch ({@link #prepareLaunch}); an activity recreated later in the same process (a
     * rotation, say) keeps serving the active UI, a trial included, instead of counting as a
     * second launch.
     */
    @Nullable
    synchronized File startDirectory() {
        if (!launchPrepared) {
            launchPrepared = true;
            return prepareLaunch();
        }
        String pending = prefs.getString(KEY_PENDING, null);
        launchIsTrial = pending != null && hasVersion(pending);
        if (launchIsTrial) {
            return versionDirectory(pending);
        }
        String current = prefs.getString(KEY_CURRENT, null);
        return hasVersion(current) ? versionDirectory(current) : null;
    }

    /**
     * Called once per launch, before the bridge loads the first page. Returns the directory to
     * serve (null: the bundled UI) and sets {@link #launchIsTrial} when this launch is a pending
     * version's trial.
     */
    @Nullable
    private File prepareLaunch() {
        launchIsTrial = false;
        // A new app binary brings its own bundled UI (and maybe new native code), so a UI
        // downloaded for the old binary is dropped, as Capacitor drops its own deploy path.
        String binaryVersion = binaryVersion();
        if (!binaryVersion.equals(prefs.getString(KEY_BINARY_VERSION, null))) {
            reset();
            prefs.edit().putString(KEY_BINARY_VERSION, binaryVersion).commit();
            return null;
        }
        String pending = prefs.getString(KEY_PENDING, null);
        if (pending != null) {
            if (!prefs.getBoolean(KEY_TRIAL_STARTED, false) && hasVersion(pending)) {
                prefs.edit().putBoolean(KEY_TRIAL_STARTED, true).commit();
                launchIsTrial = true;
                return versionDirectory(pending);
            }
            // The app died during the trial (or the files are gone): roll back before loading.
            Logger.warn("denext OTA: UI " + pending + " never confirmed its boot; rolling back.");
            return rollBackPending();
        }
        String current = prefs.getString(KEY_CURRENT, null);
        if (current != null) {
            if (hasVersion(current)) {
                return versionDirectory(current);
            }
            prefs.edit().remove(KEY_CURRENT).commit();
        }
        return null;
    }

    /** {@code activate} / {@code apply}: the (staged) version starts its trial; nothing stays staged. */
    synchronized void beginTrial(String version) {
        prefs
            .edit()
            .putString(KEY_PREVIOUS, prefs.getString(KEY_CURRENT, null))
            .putString(KEY_PENDING, version)
            .putBoolean(KEY_TRIAL_STARTED, true)
            .remove(KEY_STAGED)
            .commit();
    }

    /** {@code booted}: the pending version becomes current, and every other version is deleted (bar a staged one). */
    synchronized void confirmPending() {
        String pending = prefs.getString(KEY_PENDING, null);
        if (pending == null) {
            return;
        }
        String staged = prefs.getString(KEY_STAGED, null);
        prefs
            .edit()
            .putString(KEY_CURRENT, pending)
            .remove(KEY_PENDING)
            .remove(KEY_PREVIOUS)
            .remove(KEY_TRIAL_STARTED)
            .commit();
        File[] entries = root.listFiles();
        if (entries != null) {
            for (File entry : entries) {
                if (!entry.getName().equals(pending) && !entry.getName().equals(staged)) {
                    deleteRecursively(entry);
                }
            }
        }
    }

    /**
     * Drops the pending version (remembered as rejected) and returns the directory to serve: the
     * previous version if it is still there, otherwise null for the bundled UI.
     */
    @Nullable
    synchronized File rollBackPending() {
        String previous = prefs.getString(KEY_PREVIOUS, null);
        String target = hasVersion(previous) ? previous : null;
        String failed = prefs.getString(KEY_PENDING, null);
        SharedPreferences.Editor editor = prefs.edit();
        if (failed != null) {
            editor.putString(KEY_REJECTED, failed);
            deleteRecursively(versionDirectory(failed));
        }
        editor.remove(KEY_PENDING).remove(KEY_PREVIOUS).remove(KEY_TRIAL_STARTED);
        if (target == null) {
            editor.remove(KEY_CURRENT);
        } else {
            editor.putString(KEY_CURRENT, target);
        }
        editor.commit();
        return target == null ? null : versionDirectory(target);
    }

    /** Back to the bundled UI with no downloaded or staged versions and nothing rejected. */
    synchronized void reset() {
        prefs
            .edit()
            .remove(KEY_CURRENT)
            .remove(KEY_PENDING)
            .remove(KEY_PREVIOUS)
            .remove(KEY_TRIAL_STARTED)
            .remove(KEY_REJECTED)
            .remove(KEY_STAGED)
            .commit();
        deleteRecursively(root);
    }

    /** The running download (if any), then the bundled UI. */
    private List<LocalSource> localSources() {
        List<LocalSource> sources = new ArrayList<>();
        String current = current();
        if (hasVersion(current)) {
            final File directory = versionDirectory(current);
            final Map<String, String> index = indexOf(parseManifest(readFile(new File(directory, MANIFEST_PATH))));
            sources.add(
                new LocalSource() {
                    @Override
                    public byte[] read(String path) {
                        return readFile(new File(directory, path));
                    }

                    @Override
                    public Map<String, String> pathsBySha() {
                        return index;
                    }
                }
            );
        }
        final Map<String, String> bundledIndex = indexOf(parseManifest(readAsset(BUNDLED_ASSET_DIR + "/" + MANIFEST_PATH)));
        sources.add(
            new LocalSource() {
                @Override
                public byte[] read(String path) {
                    return readAsset(BUNDLED_ASSET_DIR + "/" + path);
                }

                @Override
                public Map<String, String> pathsBySha() {
                    return bundledIndex;
                }
            }
        );
        return sources;
    }

    /**
     * The bytes of {@code file} from a UI already on the device, when one has a file with the
     * same SHA-256 (by its manifest, or at the same path) that still verifies.
     */
    @Nullable
    private static byte[] localCopy(ManifestFile file, List<LocalSource> sources) {
        for (LocalSource source : sources) {
            List<String> candidates = new ArrayList<>();
            String byHash = source.pathsBySha().get(file.sha256);
            if (byHash != null && isSafeRelativePath(byHash)) {
                candidates.add(byHash);
            }
            if (!candidates.contains(file.path)) {
                candidates.add(file.path);
            }
            for (String candidate : candidates) {
                byte[] data = source.read(candidate);
                if (data != null && data.length == file.size && sha256Hex(data).equals(file.sha256)) {
                    return data;
                }
            }
        }
        return null;
    }

    /**
     * Off the main thread. Fetches and verifies every file into {@code <version>.partial/}
     * (copying the ones a UI on the device already has), writes the manifest next to them, then
     * renames the directory to {@code <version>/}. Any failure deletes the partial directory.
     */
    DownloadStats download(ApplyRequest request) throws OtaException {
        File partial = new File(root, request.version + ".partial");
        File destination = versionDirectory(request.version);
        deleteRecursively(partial);
        ExecutorService pool = Executors.newFixedThreadPool(MAX_CONCURRENT_DOWNLOADS);
        try {
            if (!partial.mkdirs()) {
                throw new OtaException("download", "Could not create " + partial);
            }
            final List<LocalSource> sources = localSources();
            List<Future<Boolean>> futures = new ArrayList<>();
            for (ManifestFile file : request.files) {
                futures.add(pool.submit(() -> fetchFile(file, request, sources, partial)));
            }
            DownloadStats stats = new DownloadStats();
            for (Future<Boolean> future : futures) {
                if (future.get()) {
                    stats.copied++;
                } else {
                    stats.downloaded++;
                }
            }
            writeManifest(request, partial);
            deleteRecursively(destination);
            if (!partial.renameTo(destination)) {
                throw new OtaException("download", "Could not move the UI into place.");
            }
            return stats;
        } catch (ExecutionException ex) {
            deleteRecursively(partial);
            Throwable cause = ex.getCause();
            if (cause instanceof OtaException) {
                throw (OtaException) cause;
            }
            throw new OtaException("download", cause == null ? ex.toString() : cause.toString());
        } catch (InterruptedException ex) {
            deleteRecursively(partial);
            Thread.currentThread().interrupt();
            throw new OtaException("download", "The UI download was interrupted.");
        } catch (OtaException ex) {
            deleteRecursively(partial);
            throw ex;
        } catch (IOException | JSONException ex) {
            deleteRecursively(partial);
            throw new OtaException("download", ex.toString());
        } finally {
            pool.shutdownNow();
        }
    }

    /** The version's own {@code _denext/ota.json}, so a later update can copy files from it. */
    private static void writeManifest(ApplyRequest request, File directory) throws IOException, JSONException {
        JSONArray files = new JSONArray();
        for (ManifestFile file : request.files) {
            files.put(new JSONObject().put("path", file.path).put("sha256", file.sha256).put("size", file.size));
        }
        JSONObject manifest = new JSONObject().put("version", request.version).put("files", files);
        writeFile(new File(directory, MANIFEST_PATH), manifest.toString().getBytes(StandardCharsets.UTF_8));
    }

    /** Writes one verified file into {@code directory}; returns true when it was copied from the device. */
    private static boolean fetchFile(ManifestFile file, ApplyRequest request, List<LocalSource> sources, File directory)
        throws OtaException, IOException {
        File target = new File(directory, file.path);
        if (!target.getCanonicalPath().startsWith(directory.getCanonicalPath() + File.separator)) {
            throw new OtaException("invalid", file.path + " leaves the UI directory.");
        }
        byte[] data = localCopy(file, sources);
        boolean copied = data != null;
        if (data == null) {
            data = downloadFile(file, request);
        }
        writeFile(target, data);
        return copied;
    }

    private static byte[] downloadFile(ManifestFile file, ApplyRequest request) throws OtaException, IOException {
        Uri.Builder uri = Uri.parse(request.baseUrl).buildUpon();
        for (String segment : file.path.split("/")) {
            uri.appendPath(segment);
        }
        HttpURLConnection connection = (HttpURLConnection) new URL(uri.build().toString()).openConnection();
        connection.setConnectTimeout(PER_FILE_TIMEOUT_MS);
        connection.setReadTimeout(PER_FILE_TIMEOUT_MS);
        connection.setUseCaches(false);
        for (Map.Entry<String, String> header : request.headers.entrySet()) {
            connection.setRequestProperty(header.getKey(), header.getValue());
        }
        byte[] data;
        try {
            int status = connection.getResponseCode();
            if (status != 200) {
                throw new OtaException("download", "Downloading " + file.path + " failed with HTTP " + status + ".");
            }
            try (InputStream input = connection.getInputStream()) {
                data = readAll(input);
            }
        } finally {
            connection.disconnect();
        }
        if (data.length != file.size || !sha256Hex(data).equals(file.sha256)) {
            throw new OtaException("integrity", file.path + " does not match the manifest.");
        }
        return data;
    }

    private String binaryVersion() {
        try {
            PackageInfo info = context.getPackageManager().getPackageInfo(context.getPackageName(), 0);
            // The bundled UI's version is part of the key, so a rebuild that ships a different
            // UI counts as a new binary even when versionName/versionCode were not bumped.
            String bundled = bundledVersion();
            return info.versionName + "+" + PackageInfoCompat.getLongVersionCode(info) + "+"
                + (bundled == null ? "" : bundled);
        } catch (PackageManager.NameNotFoundException ex) {
            return "";
        }
    }

    /** SHA-256 → path from a parsed manifest (empty when there is none). */
    private static Map<String, String> indexOf(@Nullable JSONObject manifest) {
        Map<String, String> index = new HashMap<>();
        JSONArray files = manifest == null ? null : manifest.optJSONArray("files");
        if (files == null) {
            return index;
        }
        for (int i = 0; i < files.length(); i++) {
            JSONObject file = files.optJSONObject(i);
            String sha = file == null ? null : file.optString("sha256", null);
            String path = file == null ? null : file.optString("path", null);
            if (sha != null && path != null && !index.containsKey(sha)) {
                index.put(sha, path);
            }
        }
        return index;
    }

    @Nullable
    private static JSONObject parseManifest(@Nullable byte[] data) {
        if (data == null) {
            return null;
        }
        try {
            return new JSONObject(new String(data, StandardCharsets.UTF_8));
        } catch (JSONException ex) {
            return null;
        }
    }

    @Nullable
    private byte[] readAsset(String path) {
        try (InputStream input = context.getAssets().open(path)) {
            return readAll(input);
        } catch (IOException ex) {
            return null;
        }
    }

    @Nullable
    private static byte[] readFile(File file) {
        if (!file.isFile()) {
            return null;
        }
        try (InputStream input = new FileInputStream(file)) {
            return readAll(input);
        } catch (IOException ex) {
            return null;
        }
    }

    private static void writeFile(File target, byte[] data) throws IOException {
        File parent = target.getParentFile();
        if (parent != null && !parent.isDirectory() && !parent.mkdirs() && !parent.isDirectory()) {
            throw new IOException("Could not create " + parent);
        }
        try (FileOutputStream output = new FileOutputStream(target)) {
            output.write(data);
        }
    }

    private static String sha256Hex(byte[] data) {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(data);
            StringBuilder hex = new StringBuilder(digest.length * 2);
            for (byte value : digest) {
                hex.append(String.format("%02x", value));
            }
            return hex.toString();
        } catch (NoSuchAlgorithmException ex) {
            throw new IllegalStateException(ex);
        }
    }

    private static byte[] readAll(InputStream input) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        byte[] buffer = new byte[65_536];
        int read;
        while ((read = input.read(buffer)) != -1) {
            output.write(buffer, 0, read);
        }
        return output.toByteArray();
    }

    private static void deleteRecursively(File file) {
        File[] children = file.listFiles();
        if (children != null) {
            for (File child : children) {
                deleteRecursively(child);
            }
        }
        //noinspection ResultOfMethodCallIgnored
        file.delete();
    }
}
