// denext-ota-template: 3 sha256=636917abaa9f5f4a779b479db47bf464b7606207053cc53446ca91107589c89d
// Generated by `denext mobile add-ota` (denext over-the-air UI updates). Safe to commit;
// re-run `denext mobile add-ota` after upgrading denext (then ship a new binary). See
// https://denext.dev/docs/desktop.

package dev.denext.ota;

import android.content.Context;
import android.content.SharedPreferences;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.util.Base64;
import androidx.annotation.Nullable;
import androidx.core.content.pm.PackageInfoCompat;
import com.getcapacitor.Logger;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.security.Signature;
import java.security.interfaces.ECPublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * The over-the-air UI's files and state. Versions live in {@code no_backup/denext-ota/<version>/}
 * (never in a device backup: a UI is re-downloadable), the state in SharedPreferences:
 *
 * <ul>
 *   <li>{@code current}: the confirmed downloaded version (null: the bundled {@code public/} UI).
 *   <li>{@code pending} / {@code previous}: a version on its trial launch, and what {@code current}
 *       was before it.
 *   <li>{@code trialAttempts}: how many launches the pending version has had without confirming its
 *       boot. A launch that finds {@link #MAX_TRIAL_ATTEMPTS} used rolls the version back unseen, so
 *       one process death does not reject a good UI, but a UI that kills the app every time is
 *       rolled back on the launch after its second try.
 *   <li>{@code rejected}: the last version rolled back; {@code apply} refuses it (code
 *       {@code rejected}) until {@code reset}, so a broken server UI cannot put the app in an
 *       apply → rollback loop.
 *   <li>{@code staged}: a version {@code download} verified into its directory, waiting for
 *       {@code activate}. It is never started on its own: launch only ever serves {@code pending}
 *       or {@code current}.
 *   <li>{@code sequence}: the highest manifest {@code sequence} accepted on this device. A lower
 *       one, or none once any was accepted, is refused (code {@code downgrade}). It survives
 *       {@code reset} and new binaries: only clearing the app's data resets it.
 *   <li>{@code binaryVersion}: the app binary the downloads belong to. A new binary brings its
 *       own bundled UI (and maybe new native code), so every download is dropped.
 * </ul>
 *
 * <p>State transitions are synchronized; {@link #download} runs off the main thread, and every
 * recursive delete runs on a background thread after a rename.
 */
final class DenextOtaStore {

    /** The {@code <meta-data>} holding the boot timeout in seconds (default 15, 1 … 600). */
    static final String BOOT_TIMEOUT_META = "dev.denext.ota.BOOT_TIMEOUT";
    /** Launches a pending version gets before it is rolled back unseen. */
    static final int MAX_TRIAL_ATTEMPTS = 2;
    /** The most files a manifest may list. */
    static final int MAX_FILES = 20_000;
    /** The most bytes a manifest's files may add up to (512 MiB). */
    static final long MAX_TOTAL_BYTES = 512L * 1024 * 1024;
    /** The longest a whole download / apply may take before it is cancelled. */
    static final long APPLY_DEADLINE_MS = 30L * 60 * 1000;
    /** The bundled UI's asset directory (Bridge.DEFAULT_WEB_ASSET_DIR). */
    static final String BUNDLED_ASSET_DIR = "public";
    /** The manifest inside a UI directory, as {@code denext export} and {@code denext ota manifest} write it. */
    static final String MANIFEST_PATH = "_denext/ota.json";

    private static final String PREFS = "denext.ota";
    private static final String KEY_CURRENT = "current";
    private static final String KEY_PENDING = "pending";
    private static final String KEY_PREVIOUS = "previous";
    /** Written by earlier templates; cleared wherever the trial state is. */
    private static final String KEY_LEGACY_TRIAL_STARTED = "trialStarted";
    private static final String KEY_TRIAL_ATTEMPTS = "trialAttempts";
    private static final String KEY_REJECTED = "rejected";
    private static final String KEY_STAGED = "staged";
    private static final String KEY_SEQUENCE = "sequence";
    private static final String KEY_BINARY_VERSION = "binaryVersion";
    private static final String TRASH_PREFIX = ".denext-ota-trash-";
    private static final int MAX_CONCURRENT_DOWNLOADS = 6;
    /** The longest a download may go without receiving a byte. */
    private static final int IDLE_TIMEOUT_MS = 30_000;
    private static final int MAX_REDIRECTS = 5;
    /**
     * The {@code <meta-data>} (inside {@code <application>}) holding the OTA public key: base64 of
     * the DER SubjectPublicKeyInfo of an ECDSA P-256 key ({@code denext mobile add-ota --public-key}).
     * Read from the app binary only.
     */
    static final String PUBLIC_KEY_META = "dev.denext.ota.PUBLIC_KEY";
    /** The group order n of NIST P-256 (secp256r1), which identifies the curve of a parsed key. */
    private static final BigInteger P256_ORDER = new BigInteger(
        "FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551",
        16
    );
    /** The hosts an unsigned UI may come from over plain http when no public key is embedded. */
    static final Set<String> LOOPBACK_HOSTS = new HashSet<>(Arrays.asList("localhost", "127.0.0.1", "::1", "[::1]"));
    /** The emulator's alias for the host machine: loopback too, but only in a debuggable build. */
    static final String EMULATOR_HOST = "10.0.2.2";

    /** Deletes discarded directories off the main thread. */
    private static final ExecutorService JANITOR = Executors.newSingleThreadExecutor((runnable) -> {
        Thread thread = new Thread(runnable, "denext-ota-janitor");
        thread.setDaemon(true);
        return thread;
    });

    private static DenextOtaStore shared;

    /** Set by {@link DenextOta#prepare} when this launch is a pending version's trial; the plugin arms the watchdog. */
    static volatile boolean launchIsTrial = false;

    static synchronized DenextOtaStore get(Context context) {
        if (shared == null) {
            shared = new DenextOtaStore(context.getApplicationContext());
        }
        return shared;
    }

    /** The longest one file may take: 30 s, plus what a 32 KiB/s link needs for its size. */
    static long fileDeadlineMs(long size) {
        return 30_000 + size * 1000 / 32_768;
    }

    static final class OtaException extends Exception {

        final String code;

        OtaException(String code, String message) {
            super(message);
            this.code = code;
        }
    }

    static final class ManifestFile {

        final String path;
        final String sha256;
        final long size;

        ManifestFile(String path, String sha256, long size) {
            this.path = path;
            this.sha256 = sha256;
            this.size = size;
        }
    }

    static final class ApplyRequest {

        final String baseUrl;
        final Map<String, String> headers;
        final String version;
        final List<ManifestFile> files;
        @Nullable
        final Long sequence;

        ApplyRequest(String baseUrl, Map<String, String> headers, String version, List<ManifestFile> files, @Nullable Long sequence) {
            this.baseUrl = baseUrl;
            this.headers = headers;
            this.version = version;
            this.files = files;
            this.sequence = sequence;
        }
    }

    /** What {@link #download} did: files fetched over the network, and files copied from the device. */
    static final class DownloadStats {

        int downloaded = 0;
        int copied = 0;
    }

    /** A UI already on the device that files can be copied from. */
    private interface LocalSource {
        /** The bytes at {@code path} inside this UI, or null. {@code path} is already validated. */
        @Nullable
        InputStream open(String path);

        /** SHA-256 → path, from this UI's own manifest. */
        Map<String, String> pathsBySha();
    }

    private final Context context;
    private final SharedPreferences prefs;
    final File root;
    @Nullable
    private String bundledVersion;
    private boolean bundledVersionRead = false;
    private boolean launchPrepared = false;
    /** Set by {@link #cancelDownload}; the download in flight stops at its next check. */
    private volatile boolean cancelRequested = false;
    /** The connections of the download in flight, so a cancel can unblock their reads. */
    private final Set<HttpURLConnection> connections = Collections.synchronizedSet(new HashSet<>());

    private DenextOtaStore(Context context) {
        this.context = context;
        this.prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
        this.root = new File(context.getNoBackupFilesDir(), "denext-ota");
        migrateLegacyRoot();
        sweepTrash(root.getParentFile());
        sweepTrash(root);
    }

    /**
     * Earlier templates kept the versions in {@code files/denext-ota} (which a device backup may
     * include). Move them to {@code no_backup/}; when that fails, drop them and forget every
     * version they held, so the app starts from its bundled UI and downloads again.
     */
    private void migrateLegacyRoot() {
        File legacy = new File(context.getFilesDir(), "denext-ota");
        if (!legacy.exists()) {
            return;
        }
        if (root.exists()) {
            // Already migrated (the old directory reappeared somehow): it holds nothing in use.
            discard(legacy);
            return;
        }
        if (legacy.renameTo(root)) {
            return;
        }
        prefs
            .edit()
            .remove(KEY_CURRENT)
            .remove(KEY_PENDING)
            .remove(KEY_PREVIOUS)
            .remove(KEY_STAGED)
            .remove(KEY_TRIAL_ATTEMPTS)
            .remove(KEY_LEGACY_TRIAL_STARTED)
            .commit();
        discard(legacy);
    }

    /** The boot timeout in ms, from {@link #BOOT_TIMEOUT_META} (seconds) or 15 s. */
    long bootTimeoutMs() {
        double seconds = 15;
        try {
            ApplicationInfo info = context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
            Object value = info.metaData == null ? null : info.metaData.get(BOOT_TIMEOUT_META);
            if (value instanceof Number) {
                seconds = ((Number) value).doubleValue();
            } else if (value instanceof String) {
                seconds = Double.parseDouble(((String) value).trim());
            }
        } catch (PackageManager.NameNotFoundException | NumberFormatException ex) {
            seconds = 15;
        }
        return (long) (Math.min(Math.max(seconds, 1), 600) * 1000);
    }

    /** Whether {@code value} is 64 lowercase ASCII hex digits. */
    static boolean isSha256(@Nullable String value) {
        return value != null && value.matches("[0-9a-f]{64}");
    }

    /**
     * The manifest version of {@code files}: SHA-256 over the {@code "<path>\t<sha256>\n"} lines
     * sorted by path ({@link String#compareTo} is UTF-16 code-unit order, as in denext's
     * {@code otaManifestVersion}).
     */
    static String manifestVersion(List<ManifestFile> files) {
        List<ManifestFile> sorted = new ArrayList<>(files);
        Collections.sort(sorted, (a, b) -> a.path.compareTo(b.path));
        StringBuilder lines = new StringBuilder();
        for (ManifestFile file : sorted) {
            lines.append(file.path).append('\t').append(file.sha256).append('\n');
        }
        return sha256Hex(lines.toString().getBytes(StandardCharsets.UTF_8));
    }

    /**
     * The manifest's {@code files}, checked one by one and against the caps (code invalid): a safe
     * path (not the manifest itself, no duplicates), a SHA-256, an integer size, at most
     * {@link #MAX_FILES} files and {@link #MAX_TOTAL_BYTES} bytes, and an index.html.
     */
    static List<ManifestFile> parseFiles(@Nullable JSONArray rawFiles) throws OtaException {
        if (rawFiles == null || rawFiles.length() == 0) {
            throw new OtaException("invalid", "The manifest is malformed.");
        }
        if (rawFiles.length() > MAX_FILES) {
            throw new OtaException("invalid", "The manifest lists more than " + MAX_FILES + " files.");
        }
        List<ManifestFile> files = new ArrayList<>();
        Set<String> seen = new HashSet<>();
        long total = 0;
        for (int index = 0; index < rawFiles.length(); index++) {
            JSONObject file = rawFiles.optJSONObject(index);
            Object path = file == null ? null : file.opt("path");
            Object sha256 = file == null ? null : file.opt("sha256");
            Long size = file == null ? null : releaseInteger(file.opt("size"), "size");
            if (
                !(path instanceof String) ||
                !isSafeRelativePath((String) path) ||
                path.equals(MANIFEST_PATH) ||
                !seen.add((String) path) ||
                !(sha256 instanceof String) ||
                !isSha256((String) sha256) ||
                size == null
            ) {
                throw new OtaException("invalid", "The manifest lists a malformed file.");
            }
            total += size;
            if (total > MAX_TOTAL_BYTES) {
                throw new OtaException("invalid", "The manifest's files add up to more than " + MAX_TOTAL_BYTES + " bytes.");
            }
            files.add(new ManifestFile((String) path, (String) sha256, size));
        }
        if (!seen.contains("index.html")) {
            throw new OtaException("invalid", "The manifest has no index.html.");
        }
        return files;
    }

    /** A JSON integer in 0 … 2^53 − 1 (null when absent); anything else is code invalid. */
    @Nullable
    static Long releaseInteger(@Nullable Object value, String name) throws OtaException {
        if (value == null || value == JSONObject.NULL) {
            return null;
        }
        if (value instanceof Number) {
            double number = ((Number) value).doubleValue();
            if (number >= 0 && number <= 9_007_199_254_740_991.0 && number == Math.rint(number)) {
                return ((Number) value).longValue();
            }
        }
        throw new OtaException("invalid", "The manifest's " + name + " is not a non-negative integer.");
    }

    /**
     * The bytes a manifest signature covers (denext's {@code otaSignaturePayload}), UTF-8 with
     * {@code \n} separators and no trailing newline. With a {@code sequence} (v2):
     * {@code "denext-ota-v2\n" + version + "\n" + ("1" | "0") + "\n" + sha256hex(notes) + "\n" +
     * sequence + "\n" + (minNative or "")}; without one (v1):
     * {@code "denext-ota-v1\n" + version + "\n" + ("1" | "0") + "\n" + sha256hex(notes)}.
     */
    static byte[] signaturePayload(String version, boolean required, String notes, @Nullable Long sequence, @Nullable Long minNative) {
        String head = version + "\n" + (required ? "1" : "0") + "\n" + sha256Hex(notes.getBytes(StandardCharsets.UTF_8));
        String text = sequence == null
            ? "denext-ota-v1\n" + head
            : "denext-ota-v2\n" + head + "\n" + sequence + "\n" + (minNative == null ? "" : String.valueOf(minNative));
        return text.getBytes(StandardCharsets.UTF_8);
    }

    /**
     * The download policy, checked before any file is fetched. With a public key embedded, the
     * manifest must carry a valid signature over {@code payload} (code signature), whatever the
     * transport; a key that is present but does not parse refuses every manifest. Without one,
     * only https, or plain http to a loopback host, is allowed (code insecure); the emulator's
     * {@code 10.0.2.2} counts as loopback only in a debuggable build. A signature protects
     * integrity only: over plain http the request headers (bearer tokens) cross the network in
     * the clear.
     */
    void checkTrust(Uri base, byte[] payload, @Nullable String signature) throws OtaException {
        String encodedKey = publicKeyMetaData();
        if (encodedKey == null) {
            String host = base.getHost() == null ? "" : base.getHost().toLowerCase(Locale.ROOT);
            boolean loopback = LOOPBACK_HOSTS.contains(host) || (EMULATOR_HOST.equals(host) && isDebuggable());
            if (!"https".equalsIgnoreCase(base.getScheme()) && !loopback) {
                throw new OtaException(
                    "insecure",
                    "Refusing an unsigned UI over plain http from " + host + "; use https or embed a public key."
                );
            }
            return;
        }
        PublicKey key = parsePublicKey(encodedKey);
        if (key == null) {
            throw new OtaException("signature", "The " + PUBLIC_KEY_META + " meta-data is not a base64 P-256 public key.");
        }
        if (!isValidSignature(key, payload, signature)) {
            throw new OtaException("signature", "The manifest signature is missing or does not verify.");
        }
    }

    /**
     * The release policy, checked after {@link #checkTrust} (so a signed manifest's values are
     * authentic) and before any file is fetched: no {@code sequence} below the highest this device
     * accepted, and none missing once one was (code downgrade); no {@code minNative} above this
     * binary's {@code versionCode} (code native_too_old).
     */
    void checkRelease(@Nullable Long sequence, @Nullable Long minNative) throws OtaException {
        Long highest = highestSequence();
        if (highest != null) {
            if (sequence == null) {
                throw new OtaException("downgrade", "The manifest has no sequence, but this device accepted sequence " + highest + ".");
            }
            if (sequence < highest) {
                throw new OtaException("downgrade", "The manifest's sequence " + sequence + " is older than " + highest + ".");
            }
        }
        long build = nativeBuild();
        if (minNative != null && minNative > build) {
            throw new OtaException("native_too_old", "This UI needs app build " + minNative + " or later; this is build " + build + ".");
        }
    }

    /** The highest manifest {@code sequence} accepted on this device, or null. */
    @Nullable
    synchronized Long highestSequence() {
        return prefs.contains(KEY_SEQUENCE) ? prefs.getLong(KEY_SEQUENCE, 0) : null;
    }

    /** This binary's {@code versionCode}, which a manifest's {@code minNative} is compared with. */
    long nativeBuild() {
        try {
            return PackageInfoCompat.getLongVersionCode(context.getPackageManager().getPackageInfo(context.getPackageName(), 0));
        } catch (PackageManager.NameNotFoundException ex) {
            return 0;
        }
    }

    private boolean isDebuggable() {
        return (context.getApplicationInfo().flags & ApplicationInfo.FLAG_DEBUGGABLE) != 0;
    }

    /** The {@link #PUBLIC_KEY_META} value, or null when the app embeds none. */
    @Nullable
    private String publicKeyMetaData() throws OtaException {
        ApplicationInfo info;
        try {
            info = context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
        } catch (PackageManager.NameNotFoundException ex) {
            throw new OtaException("signature", "Could not read the app's meta-data.");
        }
        Object value = info.metaData == null ? null : info.metaData.get(PUBLIC_KEY_META);
        if (value == null) {
            return null;
        }
        // A non-string value is kept (and then fails to parse): present but unusable fails closed.
        String text = String.valueOf(value).trim();
        return text.isEmpty() ? null : text;
    }

    /** An EC P-256 public key from base64 DER SubjectPublicKeyInfo, or null (another curve included). */
    @Nullable
    private static PublicKey parsePublicKey(String encoded) {
        try {
            byte[] spki = Base64.decode(encoded, Base64.DEFAULT);
            PublicKey key = KeyFactory.getInstance("EC").generatePublic(new X509EncodedKeySpec(spki));
            if (!(key instanceof ECPublicKey) || !P256_ORDER.equals(((ECPublicKey) key).getParams().getOrder())) {
                return null;
            }
            return key;
        } catch (IllegalArgumentException | GeneralSecurityException ex) {
            return null;
        }
    }

    /** Whether {@code signature} (base64 of the raw 64-byte r‖s) verifies over {@code payload}. */
    private static boolean isValidSignature(PublicKey key, byte[] payload, @Nullable String signature) {
        if (signature == null) {
            return false;
        }
        try {
            byte[] der = rawSignatureToDer(Base64.decode(signature, Base64.DEFAULT));
            if (der == null) {
                return false;
            }
            Signature verifier = Signature.getInstance("SHA256withECDSA");
            verifier.initVerify(key);
            verifier.update(payload);
            return verifier.verify(der);
        } catch (IllegalArgumentException | GeneralSecurityException ex) {
            return false;
        }
    }

    /**
     * WebCrypto's raw r‖s (32 + 32 bytes) as the ASN.1 DER {@code SEQUENCE { INTEGER r, INTEGER s }}
     * that {@code SHA256withECDSA} verifies (the P1363 algorithm name needs API 33). Null unless
     * {@code raw} is 64 bytes.
     */
    @Nullable
    static byte[] rawSignatureToDer(byte[] raw) {
        if (raw.length != 64) {
            return null;
        }
        byte[] r = derInteger(raw, 0);
        byte[] s = derInteger(raw, 32);
        // At most 2 × 35 bytes, so the short length form always fits.
        byte[] der = new byte[2 + r.length + s.length];
        der[0] = 0x30;
        der[1] = (byte) (r.length + s.length);
        System.arraycopy(r, 0, der, 2, r.length);
        System.arraycopy(s, 0, der, 2 + r.length, s.length);
        return der;
    }

    /** The 32 bytes at {@code offset} as a DER INTEGER: leading zeros stripped, 0x00 prepended when the high bit is set. */
    private static byte[] derInteger(byte[] raw, int offset) {
        int start = offset;
        int end = offset + 32;
        while (start < end - 1 && raw[start] == 0) {
            start++;
        }
        boolean pad = (raw[start] & 0x80) != 0;
        int length = end - start + (pad ? 1 : 0);
        byte[] out = new byte[2 + length];
        out[0] = 0x02;
        out[1] = (byte) length;
        System.arraycopy(raw, start, out, pad ? 3 : 2, end - start);
        return out;
    }

    /**
     * A forward-slash path that stays inside its directory: no empty, "." or ".." segments, no
     * backslashes, and no control characters (U+0000–U+001F, U+007F, which could forge the lines
     * the version hashes).
     */
    static boolean isSafeRelativePath(@Nullable String path) {
        if (path == null || path.isEmpty()) {
            return false;
        }
        for (int i = 0; i < path.length(); i++) {
            char c = path.charAt(i);
            if (c < 0x20 || c == 0x7f || c == '\\') {
                return false;
            }
        }
        for (String segment : path.split("/", -1)) {
            if (segment.isEmpty() || segment.equals(".") || segment.equals("..")) {
                return false;
            }
        }
        return true;
    }

    @Nullable
    synchronized String current() {
        return prefs.getString(KEY_CURRENT, null);
    }

    @Nullable
    synchronized String pending() {
        return prefs.getString(KEY_PENDING, null);
    }

    @Nullable
    synchronized String rejected() {
        return prefs.getString(KEY_REJECTED, null);
    }

    /** The staged version, while its verified directory is still there. */
    @Nullable
    synchronized String staged() {
        String staged = prefs.getString(KEY_STAGED, null);
        return hasVersion(staged) ? staged : null;
    }

    /**
     * Records a verified version as staged (and its {@code sequence} as accepted), deleting the
     * directory of the version it replaces unless that one is current, pending or bundled.
     */
    synchronized void stage(String version, @Nullable Long sequence) {
        String old = prefs.getString(KEY_STAGED, null);
        if (
            old != null &&
            !old.equals(version) &&
            !old.equals(prefs.getString(KEY_CURRENT, null)) &&
            !old.equals(prefs.getString(KEY_PENDING, null)) &&
            !old.equals(bundledVersion())
        ) {
            discard(versionDirectory(old));
        }
        SharedPreferences.Editor editor = prefs.edit().putString(KEY_STAGED, version);
        Long highest = highestSequence();
        if (sequence != null && (highest == null || sequence > highest)) {
            editor.putLong(KEY_SEQUENCE, sequence);
        }
        editor.commit();
    }

    /** The version stamped into the bundled UI ({@code public/_denext/ota.json}), if any. */
    @Nullable
    synchronized String bundledVersion() {
        if (!bundledVersionRead) {
            bundledVersionRead = true;
            JSONObject manifest = parseManifest(readAsset(BUNDLED_ASSET_DIR + "/" + MANIFEST_PATH));
            String version = manifest == null ? null : manifest.optString("version", null);
            bundledVersion = isSha256(version) ? version : null;
        }
        return bundledVersion;
    }

    File versionDirectory(String version) {
        return new File(root, version);
    }

    private boolean hasVersion(@Nullable String version) {
        return version != null && new File(versionDirectory(version), "index.html").isFile();
    }

    /**
     * The directory {@link DenextOta#prepare} starts the bridge from. The first call in a process
     * is the launch ({@link #prepareLaunch}); an activity recreated later in the same process (a
     * rotation, say) keeps serving the active UI, a trial included, instead of counting as a
     * second launch.
     */
    @Nullable
    synchronized File startDirectory() {
        if (!launchPrepared) {
            launchPrepared = true;
            return prepareLaunch();
        }
        String pending = prefs.getString(KEY_PENDING, null);
        launchIsTrial = pending != null && hasVersion(pending);
        if (launchIsTrial) {
            return versionDirectory(pending);
        }
        String current = prefs.getString(KEY_CURRENT, null);
        return hasVersion(current) ? versionDirectory(current) : null;
    }

    /**
     * Called once per launch, before the bridge loads the first page. Returns the directory to
     * serve (null: the bundled UI) and sets {@link #launchIsTrial} when this launch is a pending
     * version's trial.
     */
    @Nullable
    private File prepareLaunch() {
        launchIsTrial = false;
        // A new app binary brings its own bundled UI (and maybe new native code), so a UI
        // downloaded for the old binary is dropped, as Capacitor drops its own deploy path.
        String binaryVersion = binaryVersion();
        if (!binaryVersion.equals(prefs.getString(KEY_BINARY_VERSION, null))) {
            reset();
            prefs.edit().putString(KEY_BINARY_VERSION, binaryVersion).commit();
            return null;
        }
        String pending = prefs.getString(KEY_PENDING, null);
        if (pending != null) {
            int attempts = prefs.getInt(KEY_TRIAL_ATTEMPTS, 0);
            if (hasVersion(pending) && attempts < MAX_TRIAL_ATTEMPTS) {
                // One more try: the app died before this version confirmed its boot, which may
                // not be the version's fault (the system kills backgrounded apps).
                prefs.edit().putInt(KEY_TRIAL_ATTEMPTS, attempts + 1).commit();
                launchIsTrial = true;
                return versionDirectory(pending);
            }
            // Out of tries (or the files are gone): roll back before loading.
            Logger.warn("denext OTA: UI " + pending + " never confirmed its boot; rolling back.");
            return rollBackPending();
        }
        String current = prefs.getString(KEY_CURRENT, null);
        if (current != null) {
            if (hasVersion(current)) {
                return versionDirectory(current);
            }
            prefs.edit().remove(KEY_CURRENT).commit();
        }
        return null;
    }

    /**
     * {@code activate} / {@code apply}: the (staged) version starts its trial, which counts as its
     * first attempt; nothing stays staged.
     */
    synchronized void beginTrial(String version) {
        prefs
            .edit()
            .putString(KEY_PREVIOUS, prefs.getString(KEY_CURRENT, null))
            .putString(KEY_PENDING, version)
            .putInt(KEY_TRIAL_ATTEMPTS, 1)
            .remove(KEY_LEGACY_TRIAL_STARTED)
            .remove(KEY_STAGED)
            .commit();
    }

    /** {@code booted}: the pending version becomes current, and every other version is deleted (bar a staged one). */
    synchronized void confirmPending() {
        String pending = prefs.getString(KEY_PENDING, null);
        if (pending == null) {
            return;
        }
        String staged = prefs.getString(KEY_STAGED, null);
        prefs
            .edit()
            .putString(KEY_CURRENT, pending)
            .remove(KEY_PENDING)
            .remove(KEY_PREVIOUS)
            .remove(KEY_TRIAL_ATTEMPTS)
            .remove(KEY_LEGACY_TRIAL_STARTED)
            .commit();
        File[] entries = root.listFiles();
        if (entries != null) {
            for (File entry : entries) {
                if (!entry.getName().equals(pending) && !entry.getName().equals(staged)) {
                    discard(entry);
                }
            }
        }
    }

    /**
     * Drops the pending version (remembered as rejected) and returns the directory to serve: the
     * previous version if it is still there, otherwise null for the bundled UI.
     */
    @Nullable
    synchronized File rollBackPending() {
        String previous = prefs.getString(KEY_PREVIOUS, null);
        String target = hasVersion(previous) ? previous : null;
        String failed = prefs.getString(KEY_PENDING, null);
        SharedPreferences.Editor editor = prefs.edit();
        if (failed != null) {
            editor.putString(KEY_REJECTED, failed);
            discard(versionDirectory(failed));
        }
        editor.remove(KEY_PENDING).remove(KEY_PREVIOUS).remove(KEY_TRIAL_ATTEMPTS).remove(KEY_LEGACY_TRIAL_STARTED);
        if (target == null) {
            editor.remove(KEY_CURRENT);
        } else {
            editor.putString(KEY_CURRENT, target);
        }
        editor.commit();
        return target == null ? null : versionDirectory(target);
    }

    /**
     * Back to the bundled UI with no downloaded or staged versions and nothing rejected. The
     * accepted {@code sequence} is kept: downgrade protection outlives a reset.
     */
    synchronized void reset() {
        prefs
            .edit()
            .remove(KEY_CURRENT)
            .remove(KEY_PENDING)
            .remove(KEY_PREVIOUS)
            .remove(KEY_TRIAL_ATTEMPTS)
            .remove(KEY_LEGACY_TRIAL_STARTED)
            .remove(KEY_REJECTED)
            .remove(KEY_STAGED)
            .commit();
        discard(root);
    }

    /**
     * Renames {@code file} out of the way (instant) and deletes it on a background thread, so no
     * recursive delete runs on the caller's (often the main) thread.
     */
    private static void discard(File file) {
        if (!file.exists()) {
            return;
        }
        File trash = new File(file.getParentFile(), TRASH_PREFIX + UUID.randomUUID());
        final File target = file.renameTo(trash) ? trash : file;
        JANITOR.execute(() -> deleteRecursively(target));
    }

    /** Deletes, in the background, what an earlier process discarded but did not finish deleting. */
    private static void sweepTrash(@Nullable File directory) {
        File[] entries = directory == null ? null : directory.listFiles();
        if (entries == null) {
            return;
        }
        for (File entry : entries) {
            if (entry.getName().startsWith(TRASH_PREFIX)) {
                JANITOR.execute(() -> deleteRecursively(entry));
            }
        }
    }

    /** The running download (if any), then the bundled UI. */
    private List<LocalSource> localSources() {
        List<LocalSource> sources = new ArrayList<>();
        String current = current();
        if (hasVersion(current)) {
            final File directory = versionDirectory(current);
            final Map<String, String> index = indexOf(parseManifest(readFile(new File(directory, MANIFEST_PATH))));
            sources.add(
                new LocalSource() {
                    @Override
                    public InputStream open(String path) {
                        try {
                            return new FileInputStream(new File(directory, path));
                        } catch (IOException ex) {
                            return null;
                        }
                    }

                    @Override
                    public Map<String, String> pathsBySha() {
                        return index;
                    }
                }
            );
        }
        final Map<String, String> bundledIndex = indexOf(parseManifest(readAsset(BUNDLED_ASSET_DIR + "/" + MANIFEST_PATH)));
        sources.add(
            new LocalSource() {
                @Override
                public InputStream open(String path) {
                    try {
                        return context.getAssets().open(BUNDLED_ASSET_DIR + "/" + path);
                    } catch (IOException ex) {
                        return null;
                    }
                }

                @Override
                public Map<String, String> pathsBySha() {
                    return bundledIndex;
                }
            }
        );
        return sources;
    }

    /**
     * Copies {@code file} into {@code temp} from a UI already on the device that has a file with
     * the same SHA-256 (by its manifest, or at the same path), verifying the bytes as they stream.
     */
    private static boolean copyLocal(ManifestFile file, List<LocalSource> sources, File temp) {
        for (LocalSource source : sources) {
            List<String> candidates = new ArrayList<>();
            String byHash = source.pathsBySha().get(file.sha256);
            if (byHash != null && isSafeRelativePath(byHash)) {
                candidates.add(byHash);
            }
            if (!candidates.contains(file.path)) {
                candidates.add(file.path);
            }
            for (String candidate : candidates) {
                InputStream input = source.open(candidate);
                if (input != null && copyVerified(input, temp, file)) {
                    return true;
                }
            }
        }
        return false;
    }

    /** Streams {@code input} (closing it) into {@code target} while hashing it; true when the bytes match {@code file}. */
    private static boolean copyVerified(InputStream input, File target, ManifestFile file) {
        MessageDigest digest = sha256();
        long size = 0;
        boolean ok = true;
        try (InputStream in = input; OutputStream out = new FileOutputStream(target)) {
            byte[] buffer = new byte[65_536];
            int read;
            while ((read = in.read(buffer)) != -1) {
                size += read;
                if (size > file.size) {
                    ok = false;
                    break;
                }
                digest.update(buffer, 0, read);
                out.write(buffer, 0, read);
            }
        } catch (IOException ex) {
            ok = false;
        }
        ok = ok && size == file.size && hex(digest.digest()).equals(file.sha256);
        if (!ok) {
            //noinspection ResultOfMethodCallIgnored
            target.delete();
        }
        return ok;
    }

    /** Whether the file at {@code path} has {@code file}'s size and SHA-256 (read in chunks). */
    private static boolean matches(File path, ManifestFile file) {
        if (!path.isFile() || path.length() != file.size) {
            return false;
        }
        MessageDigest digest = sha256();
        try (InputStream in = new FileInputStream(path)) {
            byte[] buffer = new byte[65_536];
            int read;
            while ((read = in.read(buffer)) != -1) {
                digest.update(buffer, 0, read);
            }
        } catch (IOException ex) {
            return false;
        }
        return hex(digest.digest()).equals(file.sha256);
    }

    /** Stops the download in flight (from any thread): it fails with code download at its next step. */
    void cancelDownload() {
        cancelRequested = true;
        disconnectAll();
    }

    private void checkCancelled() throws OtaException {
        if (cancelRequested || Thread.currentThread().isInterrupted()) {
            throw new OtaException("download", "The UI download was cancelled.");
        }
    }

    private void disconnectAll() {
        List<HttpURLConnection> open;
        synchronized (connections) {
            open = new ArrayList<>(connections);
        }
        for (HttpURLConnection connection : open) {
            connection.disconnect();
        }
    }

    /** Deletes the {@code .partial} / {@code .tmp} directories of other versions: only the version being downloaded may resume. */
    private void removeStaleAttempts(String version) {
        File[] entries = root.listFiles();
        if (entries == null) {
            return;
        }
        for (File entry : entries) {
            String name = entry.getName();
            boolean attempt = name.endsWith(".partial") || name.endsWith(".tmp");
            if (attempt && !name.equals(version + ".partial") && !name.equals(version + ".tmp")) {
                discard(entry);
            }
        }
    }

    /**
     * Off the main thread. Fetches and verifies every file into {@code <version>.partial/} (copying
     * the ones a UI on the device already has, and keeping the ones an interrupted attempt already
     * verified there), writes the manifest next to them, then renames the directory to
     * {@code <version>/}. A failure keeps the verified files for the next attempt. Each file streams
     * to disk while it is hashed and is refused as soon as it outgrows its manifest {@code size}.
     * The whole call is bounded by {@link #APPLY_DEADLINE_MS} and stops early on {@link #cancelDownload}.
     */
    DownloadStats download(ApplyRequest request) throws OtaException {
        cancelRequested = false;
        long deadline = System.currentTimeMillis() + APPLY_DEADLINE_MS;
        removeStaleAttempts(request.version);
        File partial = new File(root, request.version + ".partial");
        File scratch = new File(root, request.version + ".tmp");
        File destination = versionDirectory(request.version);
        if ((!partial.isDirectory() && !partial.mkdirs()) || (!scratch.isDirectory() && !scratch.mkdirs())) {
            throw new OtaException("download", "Could not create " + partial);
        }
        ExecutorService pool = Executors.newFixedThreadPool(MAX_CONCURRENT_DOWNLOADS);
        try {
            final List<LocalSource> sources = localSources();
            List<Future<Boolean>> futures = new ArrayList<>();
            for (ManifestFile file : request.files) {
                futures.add(pool.submit(() -> fetchFile(file, request, sources, partial, scratch)));
            }
            DownloadStats stats = new DownloadStats();
            for (Future<Boolean> future : futures) {
                long wait = deadline - System.currentTimeMillis();
                if (wait <= 0) {
                    throw new TimeoutException();
                }
                if (future.get(wait, TimeUnit.MILLISECONDS)) {
                    stats.copied++;
                } else {
                    stats.downloaded++;
                }
            }
            checkCancelled();
            writeManifest(request, partial);
            discard(destination);
            if (!partial.renameTo(destination)) {
                throw new OtaException("download", "Could not move the UI into place.");
            }
            discard(scratch);
            return stats;
        } catch (TimeoutException ex) {
            stop(pool);
            throw new OtaException("download", "The UI update took longer than " + APPLY_DEADLINE_MS / 60_000 + " minutes.");
        } catch (ExecutionException ex) {
            stop(pool);
            Throwable cause = ex.getCause();
            if (cause instanceof OtaException) {
                throw (OtaException) cause;
            }
            throw new OtaException("download", cause == null ? ex.toString() : cause.toString());
        } catch (InterruptedException ex) {
            stop(pool);
            Thread.currentThread().interrupt();
            throw new OtaException("download", "The UI download was interrupted.");
        } catch (IOException | JSONException ex) {
            stop(pool);
            throw new OtaException("download", ex.toString());
        } finally {
            // Always first: no worker may still be writing when anything is renamed or deleted.
            stop(pool);
        }
    }

    /** Stops every worker of {@code pool} (interrupting and disconnecting them) and waits for them to finish. */
    private void stop(ExecutorService pool) {
        pool.shutdownNow();
        disconnectAll();
        try {
            pool.awaitTermination(10, TimeUnit.SECONDS);
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
    }

    /** The version's own {@code _denext/ota.json}, so a later update can copy files from it and the page can read its version. */
    private static void writeManifest(ApplyRequest request, File directory) throws IOException, JSONException {
        JSONArray files = new JSONArray();
        for (ManifestFile file : request.files) {
            files.put(new JSONObject().put("path", file.path).put("sha256", file.sha256).put("size", file.size));
        }
        JSONObject manifest = new JSONObject().put("version", request.version).put("files", files);
        File target = new File(directory, MANIFEST_PATH);
        File parent = target.getParentFile();
        if (parent != null && !parent.isDirectory() && !parent.mkdirs() && !parent.isDirectory()) {
            throw new IOException("Could not create " + parent);
        }
        try (OutputStream output = new FileOutputStream(target)) {
            output.write(manifest.toString().getBytes(StandardCharsets.UTF_8));
        }
    }

    /**
     * Puts one verified file at its path in {@code directory}; returns true when it was already
     * there from an earlier attempt or copied from the device, false when it was downloaded.
     */
    private boolean fetchFile(ManifestFile file, ApplyRequest request, List<LocalSource> sources, File directory, File scratch)
        throws OtaException, IOException {
        checkCancelled();
        File target = new File(directory, file.path);
        if (!target.getCanonicalPath().startsWith(directory.getCanonicalPath() + File.separator)) {
            throw new OtaException("invalid", file.path + " leaves the UI directory.");
        }
        if (matches(target, file)) {
            return true;
        }
        File temp = new File(scratch, UUID.randomUUID().toString());
        try {
            boolean copied = copyLocal(file, sources, temp);
            if (!copied) {
                downloadFile(file, request, temp);
            }
            File parent = target.getParentFile();
            if (parent != null && !parent.isDirectory() && !parent.mkdirs() && !parent.isDirectory()) {
                throw new IOException("Could not create " + parent);
            }
            if ((target.exists() && !target.delete()) || !temp.renameTo(target)) {
                throw new IOException("Could not move " + file.path + " into place.");
            }
            return copied;
        } finally {
            //noinspection ResultOfMethodCallIgnored
            temp.delete();
        }
    }

    /** Streams {@code file} from the server into {@code temp}, verifying its size and SHA-256 as it arrives. */
    private void downloadFile(ManifestFile file, ApplyRequest request, File temp) throws OtaException, IOException {
        Uri.Builder uri = Uri.parse(request.baseUrl).buildUpon();
        for (String segment : file.path.split("/")) {
            uri.appendPath(segment);
        }
        long deadline = System.currentTimeMillis() + fileDeadlineMs(file.size);
        HttpURLConnection connection = open(new URL(uri.build().toString()), request, file);
        try {
            long length = connection.getContentLengthLong();
            if (length > file.size) {
                throw new OtaException("integrity", file.path + " is larger than the manifest says.");
            }
            MessageDigest digest = sha256();
            long received = 0;
            try (InputStream input = connection.getInputStream(); OutputStream output = new FileOutputStream(temp)) {
                byte[] buffer = new byte[65_536];
                int read;
                while ((read = input.read(buffer)) != -1) {
                    checkCancelled();
                    received += read;
                    if (received > file.size) {
                        throw new OtaException("integrity", file.path + " is larger than the manifest says.");
                    }
                    if (System.currentTimeMillis() > deadline) {
                        throw new OtaException("download", "Downloading " + file.path + " took longer than " + fileDeadlineMs(file.size) / 1000 + " s.");
                    }
                    digest.update(buffer, 0, read);
                    output.write(buffer, 0, read);
                }
            }
            if (received != file.size || !hex(digest.digest()).equals(file.sha256)) {
                throw new OtaException("integrity", file.path + " does not match the manifest.");
            }
        } finally {
            connections.remove(connection);
            connection.disconnect();
        }
    }

    /**
     * Opens {@code url} with the request headers, following redirects only within the base URL's
     * origin (the headers, which may carry a bearer token, never reach another origin), and
     * returns the connection once it answered 200.
     */
    private HttpURLConnection open(URL url, ApplyRequest request, ManifestFile file) throws OtaException, IOException {
        URL base = new URL(request.baseUrl);
        URL current = url;
        for (int hop = 0; ; hop++) {
            checkCancelled();
            HttpURLConnection connection = (HttpURLConnection) current.openConnection();
            connections.add(connection);
            connection.setInstanceFollowRedirects(false);
            connection.setConnectTimeout(IDLE_TIMEOUT_MS);
            connection.setReadTimeout(IDLE_TIMEOUT_MS);
            connection.setUseCaches(false);
            for (Map.Entry<String, String> header : request.headers.entrySet()) {
                connection.setRequestProperty(header.getKey(), header.getValue());
            }
            int status = connection.getResponseCode();
            if (status == 200) {
                return connection;
            }
            String location = connection.getHeaderField("Location");
            connections.remove(connection);
            connection.disconnect();
            boolean redirect = status == 301 || status == 302 || status == 303 || status == 307 || status == 308;
            if (!redirect || location == null) {
                throw new OtaException("download", "Downloading " + file.path + " failed with HTTP " + status + ".");
            }
            if (hop >= MAX_REDIRECTS) {
                throw new OtaException("download", "Downloading " + file.path + " was redirected too often.");
            }
            URL next = new URL(current, location);
            if (!isSameOrigin(next, base)) {
                throw new OtaException("download", "Refusing a redirect to another origin (" + next.getHost() + ").");
            }
            current = next;
        }
    }

    /** Whether {@code a} and {@code b} have the same scheme, host and (effective) port. */
    static boolean isSameOrigin(URL a, URL b) {
        int portA = a.getPort() == -1 ? a.getDefaultPort() : a.getPort();
        int portB = b.getPort() == -1 ? b.getDefaultPort() : b.getPort();
        return a.getProtocol().equalsIgnoreCase(b.getProtocol()) && a.getHost().equalsIgnoreCase(b.getHost()) && portA == portB;
    }

    private String binaryVersion() {
        try {
            PackageInfo info = context.getPackageManager().getPackageInfo(context.getPackageName(), 0);
            // The bundled UI's version is part of the key, so a rebuild that ships a different
            // UI counts as a new binary even when versionName/versionCode were not bumped.
            String bundled = bundledVersion();
            return info.versionName + "+" + PackageInfoCompat.getLongVersionCode(info) + "+"
                + (bundled == null ? "" : bundled);
        } catch (PackageManager.NameNotFoundException ex) {
            return "";
        }
    }

    /** SHA-256 → path from a parsed manifest (empty when there is none). */
    private static Map<String, String> indexOf(@Nullable JSONObject manifest) {
        Map<String, String> index = new HashMap<>();
        JSONArray files = manifest == null ? null : manifest.optJSONArray("files");
        if (files == null) {
            return index;
        }
        for (int i = 0; i < files.length(); i++) {
            JSONObject file = files.optJSONObject(i);
            String sha = file == null ? null : file.optString("sha256", null);
            String path = file == null ? null : file.optString("path", null);
            if (sha != null && path != null && !index.containsKey(sha)) {
                index.put(sha, path);
            }
        }
        return index;
    }

    @Nullable
    private static JSONObject parseManifest(@Nullable byte[] data) {
        if (data == null) {
            return null;
        }
        try {
            return new JSONObject(new String(data, StandardCharsets.UTF_8));
        } catch (JSONException ex) {
            return null;
        }
    }

    @Nullable
    private byte[] readAsset(String path) {
        try (InputStream input = context.getAssets().open(path)) {
            return readAll(input);
        } catch (IOException ex) {
            return null;
        }
    }

    @Nullable
    private static byte[] readFile(File file) {
        if (!file.isFile()) {
            return null;
        }
        try (InputStream input = new FileInputStream(file)) {
            return readAll(input);
        } catch (IOException ex) {
            return null;
        }
    }

    private static MessageDigest sha256() {
        try {
            return MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException ex) {
            throw new IllegalStateException(ex);
        }
    }

    private static String hex(byte[] digest) {
        StringBuilder hex = new StringBuilder(digest.length * 2);
        for (byte value : digest) {
            hex.append(String.format("%02x", value));
        }
        return hex.toString();
    }

    private static String sha256Hex(byte[] data) {
        return hex(sha256().digest(data));
    }

    private static byte[] readAll(InputStream input) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        byte[] buffer = new byte[65_536];
        int read;
        while ((read = input.read(buffer)) != -1) {
            output.write(buffer, 0, read);
        }
        return output.toByteArray();
    }

    private static void deleteRecursively(File file) {
        File[] children = file.listFiles();
        if (children != null) {
            for (File child : children) {
                deleteRecursively(child);
            }
        }
        //noinspection ResultOfMethodCallIgnored
        file.delete();
    }
}
